- src/akshita/Bank1.java
> Assignment-1

- src/deepak/Calculator_Assignment1.java
> Deepak_Assignment-1

- src/pushpa/Assignment12.java
- src/pushpa/Assignment13.java
- src/pushpa/Assignment14.java
- src/pushpa/Assignment15.java
- src/pushpa/Assignment16.java
- src/pushpa/Bank.java
- src/pushpa/CheckDay.java
- src/pushpa/CheckMonths.java
- src/pushpa/MinMax.java
- src/pushpa/PrintEvenNumbers.java
- src/pushpa/StudentGrade.java
> My all assignments

- src/deepak/BankDetails_Assignment5.java
- src/deepak/BankDetails_Assignment6.java
- src/deepak/Bank_Assignment4.java
- src/deepak/CalculatorTricky_Assignment3.java
- src/deepak/CalculatorWithParam_Assignment2.java
- src/deepak/DivisibleCheck1_Assignment13.java
- src/deepak/DivisibleCheck2_Assignment14.java
- src/deepak/DivisibleCheck_Assignment12.java
- src/deepak/EvenNumberCheck_Assignment11.java
- src/deepak/Grade_Assignment8.java
- src/deepak/MaxMinNumbers_Assignment7.java
- src/deepak/Month_Assignment10.java
- src/deepak/SumDivisibleNumbers_Assignment15.java
- src/deepak/Weekday_Asssignment9.java
Deepak - All Assignments till 15th Assignment
> Deepak_Assignment2_To_Assignment15

- src/mahesh/ReverseDivBy7.java
> Test PR_Mahesh_Assignment

- src/swati/Bank.java
- src/swati/Bank2.java
- src/swati/BankDetails.java
- src/swati/BankDetails2.java
- src/swati/CalculatorWithParam.java
- src/swati/CalcultorTricky.java
- src/swati/DivisibleInReverse.java
- src/swati/DivisibleNumber.java
- src/swati/DivisibleNumber1.java
- src/swati/DivisibleNumber2.java
- src/swati/DivisibleNumber3.java
- src/swati/DivisibleNumberSum.java
- src/swati/EvenNumbers.java
- src/swati/IdentifyDay.java
- src/swati/IndetifyMonth.java
- src/swati/MinMax.java
- src/swati/Student.java
- src/swati/Student1.java
- src/swati/SumAndAverage.java
> SwatiKudale_AllAssigments

- src/onkar/Assignement2.java
> Onkar branch1

- src/onkar/Assignment11.java
- src/onkar/Assignment12.java
- src/onkar/Assignment13.java
- src/onkar/Assignment14.java
- src/onkar/Assignment15.java
- src/onkar/Assignment16.java
- src/onkar/Assignment3.java
- src/onkar/Assignment4.java
- src/onkar/Assignment5.java
- src/onkar/Assignment6.java
- src/onkar/Assignment7.java
- src/onkar/Assignment8.java
- src/onkar/Assignment8_1.java
- src/onkar/Assignment9.java
- src/onkar/Bank.java
- src/onkar/Calculator.java
- src/onkar/Student.java
Added all codes written till now
> Added all my assignments through OnkarAllAssignments branch

- src/technoCredits/Assignment2.java
> Assignment-2 : print each char of given String

- src/jagrati/Assignment19.java
- src/jagrati/ForLoopProgram.java
- src/jagrati/PrintNumber.java
> Jagrati assignment19

- src/jagrati/HighestFreqString.java
- src/jagrati/NonRepeatativeCharacte.java
first program out which is incorrect 
Second program Out
> Jagrati Assigment 20 and 21

- src/yogesh/Yogesh_Assignment22.java
> Yogesh_Assignment22

- src/yogesh/Yogesh_Assignment21.java
> Yogesh_Assignment21

- src/akshita/FrequencyEachChar.java
Akshita_Assignment20_FrequencyOfChar
> Akshita_Assignment20_FrequencyOfChar

- src/sakshi/Assignment21.java
> Sakshi_Assignment_21

- src/sayali/Assignment22.java
> Sayali_Assignment-22

- src/sayali/Assignment21.java
> Sayali_Assignment-21

- src/onkar/Assignment21.java
- src/onkar/Assignment22.java
> Onkar_Assignment 21 and 22

- src/jyoti/MaxFreq.java
> Assignment21_MaxFrequencyChar

- src/technoCredits/Assignment2.java
> Assignment-2 : Print string in reverse

- src/jyoti/Fuel.java
Added new branch with Fuel program
> Jyoti_Prac

- src/denish/Assignment19.java
> Denish_Assignment19

- src/sayali/Assignment_19.java
> Sayali_Assignment-19

- src/naresh/Frequency.java
> frequency of t in technocredits

- src/akshita/CharacterOperations.java
Akshita_Assignment19  print string "Technocredit" in reverse order with frequency of repeated Char
> Akshita_Assignment19

- src/naresh/ReverseString.java
> reverse of string technocredits

- src/roshani/Assignment19.java
> Roshni_Assignment_19 : Print Frequency of Char and Reverse String

- src/dhiraj/Assignment19.java
> Dhiraj_Assignment19

- src/shrutika/ReverseString.java
> Assignment-19:String in reverse order

- src/sakshi/Assignment19.java
> Sakshi_Assignment_19

- src/onkar/Assignment17.java
- src/onkar/Assignment18.java
> Onkar: Added Assignement 17 and 18

- src/onkar/Assignment19.java
> Onkar: Added assignment 19

- src/jaykumar/Assignment17.java
- src/jaykumar/Assignment18.java
> Jaykumar_Assignment17&18: divisibleNumbers_Sum_Average

- src/jaykumar/Assignment19.java
> Jaykumar_Assignment19: CharFrequency_CharRevOrder

- src/jyoti/Assignment19.java
- src/jyoti/AssignmentNew.java
> Assignment19:Frequency and Reverse String

- src/yogesh/Yogesh_Assignment19.java
> Yogesh_Assignment19

- src/deepak/Assignment10_Month.java
- src/deepak/Assignment11_EvenNumberCheck.java
- src/deepak/Assignment12_DivisibleCheck.java
- src/deepak/Assignment13_DivisibleCheck1.java
- src/deepak/Assignment14_DivisibleCheck2.java
- src/deepak/Assignment15_SumDivisibleNumbers.java
- src/deepak/Assignment19_StringOperation1.java
- src/deepak/Assignment1_Calculator.java
- src/deepak/Assignment2_CalculatorWithParam.java
- src/deepak/Assignment3_CalculatorTricky.java
- src/deepak/Assignment4_Bank.java
- src/deepak/Assignment5_BankDetails.java
- src/deepak/Assignment6_BankDetails.java
- src/deepak/Assignment7_MaxMinNumbers.java
- src/deepak/Assignment8_Grade.java
- src/deepak/Asssignment9_Weekday.java
Deepak_Assignment19
Screenshot:
> Deepak_Assignment19

- src/mayank/MayankAssignment19.java
> Assignment-19:printreverse

- src/swati/CharFrequency.java
- src/swati/StringInReverse.java
Assignment 19 program 1
program 2
> Swati_Assignment19_Print_reverse_order

- src/rabish/Frequency.java
- src/rabish/GitPractice.java
> Assignment19

- src/nikita/Assignment19Char.java
> Nikita_Assignment19_charfrequencyandreverse

- src/nikita/BankDetail.java
- src/nikita/BankDetails1.java
- src/nikita/Calculator.java
- src/nikita/CalculatorTricky.java
- src/nikita/CalculatorWithParam.java
- src/nikita/Divisible3.java
- src/nikita/DivisibleAvg.java
- src/nikita/EvenNumbers.java
- src/nikita/MaxMin.java
> Nikita_AllPreviousAssignments

- src/aditya/LengthOfStr.java
> Aditya_Practice example for Assignment19

- src/denish/Assignment20.java
> Denish_Assignment20

- src/jyoti/CharFrequency.java
> Assignment20_CharFrequency

- src/sakshi/Assignment20.java
> Sakshi_assignment_20

- src/mayank/AssignmentFrequency.java
- src/mayank/FrequencyChar.java
frequency of t
frequency characters
> Mayank_Assignment_20 :frequency&char

- src/jagrati/CharFreq.java
> Jagrati_Assigment20 Char Freq

- src/roshani/Assignment20.java
> Roshni_Assignment-20: Print Freq of each char

- src/yogesh/Yogesh_Assignment20.java
> Yogesh_Assignment20

- src/rahul/Assignment15_1.java
> RahulH_Assignment15_1

- src/rahul/Assignment16_1.java
> RahulH_Assignment_16

- src/shamli/Assignment12.java
> Shamli_Assignment12

- src/shamli/Assignment12.java
- src/shamli/Assignment13.java
> Shamli assignment13

- src/sayali/Assignment20.java
> Sayali_Assignment-20

- src/shrutika/CharFreq.java
> Shrutika_Assignment20-FreqOfChar

- src/nikita/AllCharFreq.java
> Nikita_Assignment20_AllCharFreq

- src/jaykumar/Assignment20.java
> Jaykumar_Assignment20: PrintFrequencyOFeachChar

- src/rahul/Assignment18_1.java
> RahulH_Assignment-18

- src/rahul/Assignment17_1.java
> RahulH_Assignment-17

- src/rabish/FreqChar.java
- src/rabish/Frequency.java
- src/rabish/GitPractice.java
> Ravish raj assignment20

- src/denish/Assignment22.java
> Denish_Assignment22

- src/denish/Assignment21.java
> Denish_Assignment21

- src/swati/Ass21CharWitMaxFrequency.java
- src/swati/CharFrequency.java
- src/swati/PrintFrequency.java
- src/swati/StringInReverse.java
> Swati assignment21

- src/pushpa/FreqOfEachCharInString.java
- src/pushpa/StringReverse.java
> Pushpa Assignment 19 and 20

- src/jaykumar/Assignment21.java
- src/jaykumar/Assignment22.java
Jaykumar_Assignment21:
Jaykumar_Assignment22:
> Jaykumar_Assignment21_22: maxCharFreq_uniqueChar

- src/sakshi/Assignment22.java
> Sakshi_Assignment_22

- src/vishal/Assignment19.java
- src/vishal/Assignment20.java
- src/vishal/Assignment21.java
- src/vishal/Assignment22.java
> Vishal assignment 21 22

- src/naresh/MaxCharFreq.java
> Naresh_Assignment21-Max frequency of character

- src/roshani/Assignment21.java
- src/roshani/Assignment22.java
> Roshni_Assignment_21_22 : Print Freq of Max Char and Print Unique Char

- src/jyoti/NonRepeatativeChar.java
> Assignment22_NonRepeatativeChar

- src/aditya/CharFreq.java
> Aditya_Assignment20

- src/subramanium/Assignment19.java
- src/subramanium/CharFreq.java
> Assignment_19 code

- src/deepak/Assignment16_DivisibleCheck3.java
- src/deepak/Assignment17_DivisibleCheck4.java
- src/deepak/Assignment18_DivisibleCheck5.java
- src/deepak/Assignment20_CharFrequency.java
- src/deepak/Assignment21_MaxFrequency.java
- src/deepak/Assignment22_NonRepeativeChars.java
Screenshots:
Assignment16-
Assignment17-
Assignment18-
Assignment20-
Assignment21-
Assignment22-
> Deepak_Assignments_16_17_18_20_21_22

- src/mayank/Assignment21.java
> Mayank_Assignment21_nonrepitive

- src/mayank/Assignment22.java
> Mayank_Assignment_22

- src/rahul/Assignment19_1.java
- src/rahul/Assignment19_2.java
Assignment19_1:
Assignment19_2:
> RahulH_Assignment-19 two programs

- src/rahul/Assignment20_1.java
> RahulH_Assignment-20

- src/yogesh/Yogesh_Assignment23.java
> Yogesh_Assignment23

- src/subramanium/Assignment20.java
>  Assignment20

- src/denish/Assignment23.java
> Denish_Assignment23

- src/swati/Ass23FindCase.java
> Swati_Assignment23_FindCountOfChar

- src/subramanium/Assignment_21.java
> Assignment_21

- src/roshani/Assignment23.java
- src/roshani/Example21.java
> Roshni_Assignment_23 : Print Count of Char

- src/pushpa/CountSplUpperLowerCharFreq.java
> Pushpa Assignment23

- src/subramanium/Assignment_22.java
> Subramanian assignment 22

- src/mayank/Assignment23.java
> Mayank_Assignment23

- src/akshita/MaxCharFrequency.java
- src/akshita/MaxFrequency.java
Akshita_Assignment21_MaxCharFrequency
> Akshita assignment21

- src/subramanium/Assignment23.java
> Subramanian_Assignment23

- src/akash/Assignment19.java
> Akash_Assignment_19

- src/onkar/Assignment23.java
> Onkar_Assignement23

- src/akshita/NonRepeatativeChar.java
Akshita_Assignment_22 Non Repetitive Character
> Akshita_Assignment_22 Non Repetative Character

- src/rahul/Assignment21_1.java
- src/rahul/Assignment21_2.java
Assignment21_1:
Assignment21_2:
> Rahul h assignment 21

- src/shrutika/UpperLowerCase.java
> Shrutika_Assignment_23

- src/akshita/Chracter.java
Akshita_Assignment_23_Character Count
> Akshita_Assignment_23_Character Count

- src/sayali/Assignment23.java
> Sayali_Assignment_23

- src/nikita/Assignment23UpperLower.java
> Nikita_Assignment_23

- src/sakshi/Assignment23.java
> Sakshi_Assignment_23

- src/nikita/Assignment21MaxfrequencyChar.java
> Nikita_Assignment_21

- src/shrutika/SumOfDigit.java
> Shrutika assignment 24

- src/mohit/Assignment_24.java
> Mohit_Assignment24 sum of digit count in string

- src/jaykumar/Assignment24.java
> Jaykumar_Assignment24: sumDigitsOfString

- src/pushpa/CountSplUpperLowerCharFreq.java
- src/pushpa/PrintSumOfDigitInString.java
> Pushpa assignment24

- src/mayank/Assignment24.java
> Mayank_Assignment24

- src/jyoti/CountStringCasesNSum.java
> Jyoti assignment24

- src/onkar/Assignment24.java
> Onkar_Assignment24

- src/rahul/Assignment23_1.java
> RahulH_Assignment-23

- src/jagrati/Assignment24.java
> Jagrati_Assignment_24

- src/denish/Assignment24.java
> Denish_Assignment24

- src/yogesh/Yogesh_Assignment24.java
> Yogesh_Assignment24

- src/deepak/Assignment23_GetCharacterTypeCount.java
> Deepak_Assignment_23

- src/jaykumar/Assignment23.java
> Jaykumar_Assignment23: charCaseCount

- src/mohit/Assignment23_CountOfCase.java
- src/mohit/PrintCharactersOfString.java
> Mohit23_Assignment case count

- src/harshada/MaxFrequency.java
- src/harshada/NonRepeatation.java
- src/harshada/WhatCase.java
> Harshada assignment 23

- src/nikita/Assignment22NonRepeatChar.java
> Nikita_Assignment_22

- src/rahul/Assignment24_1.java
> RahulH_Assignment-24

- src/mahesh/Calculator.java
FYI - This Assignment is already reviewed in Skype, please approve and merge this PR.
> Mahesh_Assignment_01

- src/jyoti/Assignment23.java
> Jyoti_Assignment23

- src/sayali/Assignment24.java
> Sayali_Assignment_24

- src/deepak/Assignment24_DigitSumInString.java
> Deepak_Assignment_24

- src/naresh/Assignment24.java
> Naresh_Assignment_24[25 min]

- src/naresh/Assignment_23.java
> Naresh_Assignment_23_[25Min]

- src/mahesh/CalculatorTricky.java
FYI - This Assignment is already reviewed in Skype, please approve and merge this PR
> Mahesh_Assignment_3.1

- src/mahesh/Bank1.java
FYI - This Assignment is already reviewed in Skype, please approve and merge this PR
> Mahesh_Assignment_3.2

- src/mahesh/Assignment4Bank.java
Please review this PR and merge if approved.
> Mahesh_Assignment_4

- src/mahesh/Assignment5BankDetails.java
Please review this PR and merge if approved.
> Mahesh_Assignment_5

- src/jagrati/Assignment27.java
> Jagrati_Assignment27

- src/onkar/Assignment26.java
>  Onkar_Assignment26

- src/onkar/Assignment25.java
> Onkar_Assignment25

- src/jagrati/Assignment26.java
> Jagrati_Assignment26

- src/jaykumar/Assignment29.java
> Jaykumar_Assignment29

- src/jaykumar/Assignment28.java
> Jaykumar_Assignment28

- src/jaykumar/Assignment26.java
> Jaykumar_Assignment26

- src/jaykumar/Assignment25.java
> Jaykumar_Assignemnt25

- src/jagrati/Assignment25.java
> Jagrati_Assignment25

- src/swati/Ass29PrintLastNonRepetitiveChar.java
> Swati_Assignment29

- src/swati/Ass28PrintFreqOfFirstNonRepetitiveChar.java
> Swati_Assignment28

- src/swati/Ass27PrintFreqOfFirstRepetitiveChar.java
> Swati_Assignment27

- src/swati/Ass26PrintFreqOfCharUsingWhileLoop.java
> Swati_Assignment26

- src/denish/Assignment29.java
> Denish_Assignment29

- src/swati/Ass25PrintFreqOfCharUsingForLoop.java
> Swati_Assignment25

- src/akshita/CharFreq.java
- src/akshita/FrequencyCharNested.java
Akshita_Assignment_25 print the frequency of all character using nested for loop.
> Akshita_Assignment_25

- src/swati/Ass23FindCase.java
- src/swati/Ass24SumOfDigits.java
> Swati_Assignment24_Corrected23AssignmentasComments_And_PushedAss24

- src/jyoti/Assignment29.java
> Jyoti_Assignment29

- src/jyoti/Assignment28.java
> Jyoti_Assignment28

- src/jyoti/Assignment27.java
> Jyoti_Assignment27

- src/jyoti/Assignment26.java
> Jyoti_Assignment26

- src/yogesh/Yogesh_Assignment28.java
> Yogesh_Assignment28

- src/jyoti/Assignment25.java
> Jyoti_Assignment25

- src/yogesh/Yogesh_Assignment27.java
> Yogesh_Assignment27

- src/jagrati/Assignment29.java
> Jagrati_Assignment29

- src/yogesh/Yogesh_Assignment26.java
> Yogesh_Assignment26

- src/yogesh/Yogesh_Assignment25.java
> Yogesh_Assignment25

- src/jagrati/Assignment28.java
> Jagrati_Assignment28

- src/onkar/Assignment28.java
> Onkar_Assignment28

- src/onkar/Assignment27.java
> Onkar_Assignment27

- src/akshita/LastNonRepetative.java
Akshita_Assignment_29 last non repetitive charact
er
> Akshita_Assignment_29

- src/akshita/CharFreq.java
- src/akshita/Chracter.java
- src/akshita/FreqCharWhileLoop.java
- src/akshita/FrequencyCharNested.java
Akshita_Assignment_26 print frequency of character using while loop
> Akshita_Assignment_26

- src/akshita/CharFreq.java
- src/akshita/Chracter.java
- src/akshita/FirstNonRepetative.java
- src/akshita/FreqCharWhileLoop.java
- src/akshita/FrequencyCharNested.java
Akshita_Assignment_27 frequency of first repetitive character
> Akshita_Assignment_27

- src/naresh/Assignment29.java
> Naresh_Assignment29_Print the last non repeatative character using[8min]

- src/naresh/Assignment28.java
> Naresh_assignment28_Print the first non repeatative character[12min]

- src/naresh/Assignment26.java
> Naresh_assignment26_Print the freq of all character[15min]

- src/naresh/Assignment25.java
> Naresh_Assignment_25_Print the freq of all character[25min]

- src/onkar/Assignment29.java
> Onkar_Assignment29

- src/technoCredits/Example23.java
- src/technoCredits/Example24.java
- src/technoCredits/interview/Bank.java
- src/technoCredits/interview/CharFreq.java
- src/technoCredits/interview/Example1.java
> Technocredits_1709

- src/shrutika/LastNonRepeatativeChar.java
> Shrutika_Assignment_29

- src/shrutika/FirstNonrepeatativeChar.java
> Shrutika_Assignment_28

- src/shrutika/CharFreqWhileLoop.java
> Shrutika_Assignment_26

- src/shrutika/CharFreqForLoop.java
> Shrutika_Assignment_25

- src/mahesh/Assignment28.java
> Mahesh_Assignment_28

- src/mahesh/Assignment27.java
> Mahesh_Assignment_27

- src/roshani/Assignment29.java
> Roshni_Assignment_29 : Print last non-repeatative char

- src/roshani/Assignment28.java
> Roshni_Assignment_28 : Print first non-repeatative char

- src/roshani/Assignment26.java
> Roshni_Assignment_26 : Print freq of all char using while loop

- src/roshani/Assignment25.java
> Roshni_Assignment_25 : Print Freq of all char using nested for loop

- src/sayali/Assignment29.java
> Sayali_Assignment_29

- src/narendra/ToFindSumOfDigitsFromString.java
> Narendra_Assignment-24

- src/narendra/GetCountFromGivenString.java
> Narendra_Assignment-23

- src/sayali/Assignment28.java
> Sayali_Assignment_28

- src/narendra/ToGetNonRepetativeChar.java
> Narendra_Assignment-22

- src/sayali/Assignment27.java
> Sayali_Assignment_27

- src/narendra/ToGetFirstMaxFreqChar.java
- src/narendra/ToGetLastMaxFreqChar.java
======================================================
> Narendra_Assignment-21

- src/sayali/Assignment26.java
> Sayali_Assignment_26

- src/sayali/Assignment25.java
> Sayali_Assignment_25

- src/mahesh/Assignment26CharFreqWhileLoop.java
> Mahesh_Assignment_26

- src/narendra/ToDisplayFrequecnyOfEachChar.java
> Narendra_Assignment-20

- src/narendra/ToDisplayFreqencyOfChar.java
- src/narendra/ToDisplayStringInReverseOrder.java
===============================================
> Narendra_Assignment-19

- src/sumeet/Assignment10.java
> Sumit_Assignment10

- src/mayank/Assignment25.java
> Mayank_Assignment25

- src/mayank/Assignment26.java
> Mayanl_Assignment26

- src/mayank/Assignment27.java
> Mayank_Assignment27

- src/mayank/Assignment28.java
> Mayank_Assignment28_firstNonRepeative

- src/deepak/Assignment25_CharFrequencyUnique.java
> Deepak_Assignment25

- src/deepak/Assignment26_CharFrequencyUniqueWhileLoop.java
> Deepak_Assignment26

- src/deepak/Assignment27_FirstRepetitiveChar.java
> Deepak_Assignment27

- src/deepak/Assignment28_FistNonRepetitiveChar.java
> Deepak_Assignment28

- src/deepak/Assignment29_LastNonRepetitiveChar.java
> Deepak_Assignment29

- src/mohit/Assignment_21.java
> Mohit_Assignment_21

- src/nivedita/A1Bank.java
- src/nivedita/A2CalWithParam.java
- src/nivedita/A3CalTotal.java
- src/nivedita/A4SetInfo.java
- src/nivedita/A5BankTrans.java
> Nivedita_Assignment_1_5

- src/nivedita/A10MonthDetails.java
- src/nivedita/A6BankCon.java
- src/nivedita/A7MaxMin.java
- src/nivedita/A8StudentGrade.java
- src/nivedita/A9WeekDetails.java
> Nivedita_Assignment_6_10

- src/nivedita/A11EvenNum.java
- src/nivedita/A12DivisibleNum.java
- src/nivedita/A13DivisibleNum.java
- src/nivedita/A15ExpSum.java
> Nivedita_Assignment_11_15

- src/nivedita/A17DivisibleNum.java
- src/nivedita/A18SumAvg.java
- src/nivedita/A19ReverseString.java
> Nivedita_Assignment_17_19

- src/nivedita/A23FindCount.java
> Nivedita_Assignment_23

- src/nivedita/A24SumDigit.java
> Nivedita_Assignment_24

- src/nivedita/A25PrintFreq.java
> Nivedita_Assignment_25

- src/nivedita/A26PrintFreq.java
> Nivedita_Assignment_26

- src/nivedita/A27RepFreq.java
> Nivedita_Assignment_27

- src/nivedita/A28PrintNonRep.java
> Nivedita_Assignment_28

- src/nivedita/A29LastNonRep.java
> Nivedita_Assignment_29

- src/vishal/Assignment23.java
- src/vishal/Assignment24.java
> “Vishal_Assignment_23-24”

- src/vishal/Assignment23.java
- src/vishal/Assignment24.java
- src/vishal/Assignment25.java
- src/vishal/Assignment26.java
> Vishal assignment 25 26

- src/vishal/Assignment23.java
- src/vishal/Assignment24.java
- src/vishal/Assignment25.java
- src/vishal/Assignment26.java
- src/vishal/Assignment27.java
- src/vishal/Assignment28.java
- src/vishal/Assignment29.java
> Vishal assignment 27 28 29

- src/denish/Assignment30.java
> Denish_Assignment_30

- src/swati/Ass30ReturnAllUpperCaseChar.java
> Swati_Assignment_30

- src/jagrati/Assignment30.java
- src/jagrati/Assignment31.java
> Jagrati_Assignment_30

- src/yogesh/Yogesh_Assignment23.java
- src/yogesh/Yogesh_Asssignment30.java
> Yogesh_Assignment30

- src/shamli/Assignment14.java
> Shamli_Assignment14

- src/roshani/Assignment30.java
> Roshni_Assignment_30 : Return all uppercase char from given input

- src/shamli/Assignment14.java
- src/shamli/Assignment15.java
> Shamli assignment15

- src/shamli/Assignment14.java
- src/shamli/Assignment15.java
- src/shamli/Assignment16.java
> Shamli assignment16

- src/shamli/Assignment14.java
- src/shamli/Assignment15.java
- src/shamli/Assignment17.java
> Shamli assignment17

- src/harshada/Sum0fDigits.java
> Harshada_Assignment_24

- src/jaykumar/Assignment30.java
> Jaykumar_Assignment30

- src/harshada/CharFreqOnce.java
> Harshada_Assignment_25

- src/harshada/AllCharFreqWhile.java
> Harshada_Assignment_26

- src/onkar/Assignment30.java
> Onkar_assignment30

- src/shrutika/UpperCaseAssig30.java
> Shrutika assignment 30

- src/shamli/Assignment18.java
> Shamli_Assignment18

- src/akshita/ReturnUppercase.java
Akshita_Assignment_30 Return all uppercase from given in
put
> Akshita_Assignment_30

- src/jyoti/Assignment30.java
> Jyoti_Assignment30

- src/harshada/FirstRepChar.java
Output: Frequency of first repetitive character
> Harshada_Assignment_27

- src/harshada/FirstNonRepChar.java
Output : first non repetitive character using while loop
> Harshada_Assignment_28

- src/harshada/LastNonRepChar.java
Output: last non repeatative character using while loop.
> Harshada_Assignment_29

- src/harshada/PrintUpperCaseChar.java
Output: Write a method which takes input and return to return all Uppercase from given input.
> Harshada_Assignment_30

- src/deepak/Assignment30_UpperCaseString.java
> Deepak_Assignment30

- src/swati/Ass31AllUpperCaseUsingAscii.java
> Swati_Assignment_31

- src/shamli/Assignment18.java
- src/shamli/Assignment19.java
> Shamli assignment19

- src/swati/Ass32PrintUppLowDigInInput.java
> Swati_Assignment_32

- src/sayali/Assignment30.java
> Sayali_Assignment_30

- src/shrutika/AsciiAssig31.java
> Shrutika_Assignment_31

- src/sayali/Assignment31.java
> Sayali_Assignment_31

- src/denish/Assignment31.java
> Denish_Assignment_31

- src/sayali/Assignment32.java
> Sayali_Assignment_32

- src/denish/Assignment32.java
> Denish_Assignment_32

- src/jaykumar/Assignment31.java
> Jaykumar_Assignment31

- src/roshani/Assignment31.java
> Roshni_Assingment_31 : Return uppercase letters from given string

- src/jaykumar/Assignment32.java
> Jaykumar_Assignment32

- src/jyoti/Ascii/Assignment31.java
> Jyoti_Assignment31

- src/jyoti/Ascii/Assignment32.java
> Jyoti_Assignment32

- src/mayank/Assignment30.java
> Mayank_Assignment30

- src/mayank/Assignment31.java
> Mayank_Assignment31

- src/jagrati/Assignment31.java
> Jagrati_Assignment_31

- src/mayank/Assignment32.java
> MAyank_Assignment32

- src/pavan/RevarseOrder.java
- src/pavan/UppercaseFinder.java
> Pavan_Assignment31

- src/jagrati/Assignment32.java
> Jagrati_Assignment_32

- src/yogesh/Yogesh_Assignment31.java
> Yogesh_Assignment31

- src/yogesh/Yogesh_Assignment32.java
> Yogesh_Assignment32

- src/shamli/Assignment20.java
> Shamli_Assignment20

- src/akshita/CapitalCharAscii.java
Akshita_Assignment_31 Uppercase from given input using ASCII
> Akshita_Assignment_31

- src/akshita/UcLcDigitASCII.java
Akshita_Assignment_32 Uppercase, Lowercase  and Digit from given input using ASCII
> Akshita_Assignment_32

- src/shrutika/AsciiValuesAssig32.java
> Shrutika_Assignment_32

- src/shamli/Assignment20.java
- src/shamli/Assignment21.java
> Shamli assignment21

- src/shamli/Assignment20.java
- src/shamli/Assignment21.java
- src/shamli/Assignment22.java
> Shamli assignment22

- src/naresh/Assignment30.java
> Naresh_Assignment30_Uppercase by return value_[15min]

- src/onkar/Assignment31.java
> Onkar_Assignment31

- src/shamli/Assignment20.java
- src/shamli/Assignment21.java
- src/shamli/Assignment22.java
- src/shamli/Assignment23.java
> Shamli assignment23

- src/onkar/Assignment32.java
> Onkar_Assignment32

- src/shamli/Assignment20.java
- src/shamli/Assignment21.java
- src/shamli/Assignment22.java
- src/shamli/Assignment23.java
- src/shamli/Assignment24.java
> Shamli assignment24

- src/pushpa/Assignment25.java
> Pushpa_Assignment25

- src/pushpa/Assignment25.java
- src/pushpa/Assignment26.java
> Pushpa assignment26

- src/pushpa/Assignment25.java
- src/pushpa/Assignment26.java
- src/pushpa/Assignment27.java
> Pushpa assignment27

- src/pushpa/Assignment25.java
- src/pushpa/Assignment26.java
- src/pushpa/Assignment27.java
- src/pushpa/Assignment28.java
> Pushpa assignment28

- src/pushpa/Assignment25.java
- src/pushpa/Assignment26.java
- src/pushpa/Assignment27.java
- src/pushpa/Assignment28.java
- src/pushpa/Assignment29.java
> Pushpa assignment29

- src/pushpa/Assignment25.java
- src/pushpa/Assignment26.java
- src/pushpa/Assignment27.java
- src/pushpa/Assignment28.java
- src/pushpa/Assignment29.java
- src/pushpa/Assignment30.java
> Pushpa assignment30

- src/pushpa/Assignment25.java
- src/pushpa/Assignment26.java
- src/pushpa/Assignment27.java
- src/pushpa/Assignment28.java
- src/pushpa/Assignment29.java
- src/pushpa/Assignment30.java
- src/pushpa/Assignment31.java
> Pushpa assignment31

- src/onkar/ProgramTest1.java
> Onkar_ProgrammingTest1

- src/pushpa/Assignment25.java
- src/pushpa/Assignment26.java
- src/pushpa/Assignment27.java
- src/pushpa/Assignment28.java
- src/pushpa/Assignment29.java
- src/pushpa/Assignment30.java
- src/pushpa/Assignment31.java
- src/pushpa/Assignment32.java
> Pushpa assignment32

- src/jaykumar/ProgrammingTest1.java
> Jaykumar_Programming_Test_1

- src/shamli/Assignment20.java
- src/shamli/Assignment21.java
- src/shamli/Assignment22.java
- src/shamli/Assignment23.java
- src/shamli/Assignment24.java
- src/shamli/ProgrammingTest1.java
> Shamli programming test1

- src/shrutika/ProgramingTest1.java
> Shrutika_Prgrammning_Test_1

- src/rahul/ProgrammingTest1/Exam1.java
> Rahul programming test 1

- src/akshita/RearrangeChar.java
Akshit_Programming_Test_1  Arrange string in order of digit, lowercase and uppercase
> Akshit_Programming_Test_1

- src/jagrati/ProgramTest1.java
> Jagrati_Programing_Test_1

- src/gaurang/Test1.java
> Gaurang_test_1

- src/roshani/ProgrammingTest1.java
> Roshni_Programming_Test_1 : Rearranged String

- src/mahesh/ProgramTest1.java
> Mahesh_Programming_Test_1

- src/denish/ProgramTest1.java
> Denish_Programming_Test_1

- src/yogesh/Yogesh_Programming_Test_1.java
> Yogesh_Programming_Test_1

- src/hetal/Assignment_22.java
> Hetal_Assignment_22

- src/sumeet/Assignment11.java
> Sumit_Assignment11 :Even Number

- src/naresh/Assignment33.java
> Naresh_programming_test1_ rearrange string[20min]

- src/naresh/Assignment34.java
> Naresh_programming_test2_sum_of

- src/shrutika/ProgramTest2.java
> Shrutika_Program_Test2

- src/hetal/Assignment23.java
> Hetal_Assignment_23

- src/shamli/Assignment25.java
> Shamli_Assignment25

- src/jyoti/Programming_Test1.java
> Jyoti_Programming_Test1

- src/deepak/ProgrammingTest1_Deepak.java
> Deepak_Programming_Test_1

- src/deepak/Assignment31_UpperCaseStringASCII.java
> Deepak_Assignment_31

- src/deepak/Assignment32_CharacterTypeUsingASCII.java
> Deepak_Assignment_32

- src/pushpa/ProgrammingTest1.java
> Pushpa Programming Test1

- src/pushpa/ProgrammingTest2.java
> Pushpa Programming Test2

- src/sayali/Programming_Test1.java
> Sayali_Programming_Test_1

- src/sayali/Programming_Test2.java
> Sayali_Programming_Test_2

- src/swati/Test1ProgRearrangeString.java
> Swati_Programming_Test_1

- src/swati/Test2ProgSumOfDigitRearrangeString.java
> Swati_Programming_Test_2

- src/narendra/Program_Test1_RearrangeString.java
> Narendra_Programming_Test-1

- src/narendra/Program_Test2_RearrangeString.java
> Narendra_Programming_Test-2

- src/narendra/Assignment25_GetFrequencyOfEachCharNestedForLoop.java
> Narendra-Assignment-25

- src/narendra/Assignment26_GetFrequencyOfEachCharWhileLoop.java
> Narendra-Assignment-26

- src/narendra/Assignment27_GetFreqOfFirstfRepChar.java
> Narendra-Assignment-27

- src/narendra/Assignment28_GetFirstNonRepChar.java
> Narendra-Assignment-28

- src/narendra/Assignment29_GetLastNonRepChar.java
> Narendra-Assignment-29

- src/narendra/Assignment30_To_Return_All_Uppercase.java
> Narendra-Assignment-30

- src/pushpa/Assignment33.java
> Pushpa Assignment33

- src/pushpa/Assignment34.java
> Pushpa Assignment34

- src/pushpa/Assignment35.java
> Pushpa Assignment35

- src/pushpa/Assignment36.java
> Pushpa Assignment36

- src/swati/Ass33PrintSumOfAllNumbers.java
> Swati_Assignment_33

- src/swati/Ass34RetrunPositiveDiffOfEvenNum.java
> Swati_Assignment_34

- src/denish/Assignment33.java
> Denish_Assignment_33

- src/denish/Assignment34.java
> Denish_Assignment_34

- src/denish/Assignment35.java
> Denish_Assignment_35

- src/denish/Assignment36.java
> Denish_Assignment_36

- src/nivedita/A31ReturnAscii.java
> Nivedita_Assignment_31

- src/nivedita/A32PrintData.java
> Nivedita_Assignment_32

- src/array/EvenUsingArray.java
Akshita_Assignment_33 Print sum of even number
> Akshita_Assignment_33

- src/swati/Ass36SwapElementsOfGivenArray.java
> Swati_Assignment_36

- src/aditya/Array/Assignment34.java
> Aditya Assignment 34

- src/aditya/Array/Assignment33.java
- src/aditya/CharFreq.java
> Aditya Asiignmnet33

- src/naresh/Assignment33.java
- src/naresh/Assignment34.java
- src/naresh/Assignment35.java
- src/naresh/Assignment36.java
[Assignment 33]
[Assignment34]
[Assignment 35]
[Assignment 36]
> Naresh-Assignment33_print_SumOfThEven_No[15min]

- src/onkar/Assignment33.java
> Onkar_Assignment33

- src/onkar/Assignment34.java
> Onkar_Assignment34

- src/sayali/Assignment33.java
> Sayali_Assignment_33

- src/onkar/Assignment35.java
> Onkar_Assignment35

- src/mohit/Assignment_33.java
> Mohit_Assignment_33

- src/sayali/Assignment34.java
> Sayali_Assignment_34

- src/mohit/Assignment_34.java
> Mohit_Assignment_34

- src/onkar/Assignment36.java
> Onkar_Assignment36

- src/mohit/Assignment_35.java
> Mohit_Assignment_35

- src/sayali/Assignment35.java
> Sayali_Assignment_35

- src/array/DiffEvenOdd.java
Akshita_Assignment_3  Difference of all even number and odd number from given array![image](https://github.com/KrishnaKTechnocredits/Sep23JAVA/assets/144511501/61ea9c10-d85d-48b2-8030-a247fb0d5894)
4
> Akshita_Assignment_34

- src/sayali/Assignment36.java
> Sayali_Assignment_36

- src/mohit/Assignment_36.java
> Mohit_Assignment_36

- src/narendra/Assignment30_ToDisplayUpperCase_UsingAscii.java
> Narendra-Assignment-31

- src/narendra/Assignment32_ToDisplayUpperLowerDigit_UsingAscii.java
> Narendra-Assignment-32

- src/rahul/ProgrammingTest2/Exam2.java
> RahulH_Programming_Test_1 - program 2

- src/array/Name_FirstLetter.java
Akshita_Assignment_35 name and first letter from given array
> Akshita_Assignment_35

- src/array/SwapFirstLastofArray.java
Akshita_Assignment_36 Swap first and last element of array
> Akshita_Assignment_36

- src/gaurang/Assignment20.java
> Assignment_20

- src/gaurang/Assignment19.java
> Assignment_19

- src/yogesh/Yogesh_Assignment33.java
> Yogesh_Assignment33

- src/yogesh/Yogesh_Assignment35.java
> Yogesh_Assignment35

- src/yogesh/Yogesh_Assignment36.java
> Yogesh_Assignment36

- src/nivedita/A33PrintNum.java
> Nivedita_Assignment_33

- src/nivedita/A34ReturnArr.java
> Nivedita_Assignment_34

- src/nivedita/A35PrintArr.java
> Nivedita_Assignment_35

- src/nivedita/A36SwapArr.java
> Nivedita_Assignment_36

- src/nivedita_test/Nivedia_Program_test_1.java
- src/nivedita_test/Nivedia_test_1.java
> Nivedita programming test 1

- src/jaykumar/Assignment33.java
> Jaykumar_Assignment33

- src/jaykumar/Assignment34.java
> Jaykumar_Assignment34

- src/jaykumar/Assignment35.java
> Jaykumar_Assignment35

- src/jaykumar/Assignment36.java
> Jaykumar_Assignment36

- src/mayank/Mayank_ProgrammingTest1.java
> Mayank_ProgrammingTest1

- src/mayank/Mayank_ProgrammingTest2.java
> Mayank_ProgramingTest2

- src/deepak/Assignment33_ArrayEvenNumSum.java
> Deepak_Assignment_33

- src/deepak/Assignment34_ArrayDifferenceOfSum.java
> Deepak_Assignment_34

- src/deepak/Assignment35_ArrayNameWithFirstLetter.java
> Deepak_Assignment_35

- src/deepak/Assignment36_ArrayStringFisrtLastSwap.java
> Deepak_Assignment_36

- src/rahul/Assignment33_1.java
> Rahul_Assignment-33

- src/rahul/Assignment34_1.java
> Rahul assignment 34

- src/mayank/Assignment33.java
> Mayank_Assignment33

- src/mayank/Assignment34.java
> Mayank_Assignment34

- src/mayank/Assignment35.java
assignment 35
Print name and its first letter from given array.
input :  { "Sayli", "deepak", "Nivedita", "Yogesh" }
output : Sayli -> S
deepak -> d
Nivedita -> N
Yogesh -> Y
> Mayank_Assignment35

- src/rahul/Assignment35_1.java
> Rahul_Assignment-35

- src/rahul/Assignment36_1.java
> Rahul assignment 36

- src/jyoti/Assignment33.java
> Jyoti_Assignment33

- src/rahul/Assignment36_1.java
> Rahul_Assignment-36 - Updated the code as output was incorrect

- src/shrutika/ArryEvenNumA33.java
> Shrutika_Assignment_33

- src/rahul/Assignment30_1.java
> Rahul_Assignment-30

- src/rahul/Assignment31_1.java
> Rahul_Assignment-31

- src/rahul/Assignment32_1.java
> Rahul_Assignment-32

- src/shrutika/PositiveSumA34.java
> Shrutika_Assignment_34

- src/shrutika/ArryFirstLetterOfArryA35.java
> Shrutika_Assignment_35

- src/shrutika/ArrySwapA36.java
> Shrutika_Assignment_36

- src/roshani/Assignment33.java
> Roshni_Assignment_33 : Sum of even numbers from given array

- src/roshani/Assignment34.java
> Roshni_Assignment_34 : Return positive diff from given array

- src/roshani/Assignment35.java
> Roshni_Assignment_35 : Print name and its first letter from given array

- src/roshani/Assignment36.java
> Roshni_Assignment_36 : Swap

- src/narendra/Assignment33_GetSumOfEvenNumFromArray.java
> Narendra-Assignment-33

- src/narendra/Assignment34_GetDiffOfSumOfEvenOddNumFromArray.java
> Narendra-Assignment-34

- src/narendra/Assignment35_GetNamePrintedArray.java
> Narendra-Assignment-35

- src/narendra/Assignment36_ToSwapFirstAndLastElementFromStringArray.java
> Narendra-Assignment-36

- src/gaurang/A.java
- src/gaurang/B.java
- src/gaurang/Case1Opps.java
- src/gaurang/Case2Oops.java
- src/gaurang/Case3Oops.java
- src/gaurang/Case4Oops.java
- src/gaurang/Case5Oops.java
- src/gaurang/Case6Oops.java
> AllClass_of_oops

- src/gaurang/Assignment22.java
> Assignment_22

- src/gaurang/Assignment23.java
> Assignment23

- src/gaurang/Assignment24.java
> Assignment24

- src/denish/A.java
- src/denish/B.java
- src/denish/Case1.java
- src/denish/Case2.java
- src/denish/Case3.java
- src/denish/Case4.java
- src/denish/Case5.java
- src/denish/Case6.java
> Denish_AllOpps_Case

- src/gaurang/Assignment25.java
> Assignment25

- src/hetal/Assignment_33.java
> Hetal_Assignment33

- src/yogesh/B.java
- src/yogesh/Yogesh_Assignment37.java
> Yogesh_Assignment37

- src/jagrati/Assignment33.java
> Jagrati_Assignment_33

- src/sumeet/Assignment12.java
> Sumit_Assignment12: divisible by 5 and 3

- src/sumeet/Assignment13.java
> Sumit_Assignment13 : Div by 7 and 13

- src/sumeet/Assignment14.java
> Sumit_Assignment14: Last number div by 5 and 9

- src/sumeet/Assignment15.java
> Sumit_Assignment15: sumOfNumderDivByFiveAndTen

- src/jagrati/Assignment34.java
> Jagrati_Assignment_34

- src/sumeet/Assignment16.java
> Sumit_Assignment16: First 3 numbers divisible by 3 and 4

- src/hetal/A.java
- src/hetal/B.java
- src/hetal/Case1.java
- src/hetal/Case2.java
- src/hetal/Case3.java
- src/hetal/Case4.java
- src/hetal/Case5.java
- src/hetal/Case6.java
> Hetal_Asiignment_37

- src/jagrati/Assignment36.java
> Jagrati_Assignment_36

- src/swati/Ass37InheritanceDemoEmployeeClass.java
- src/swati/Ass37InheritanceDemoManagerClass.java
> Swati_Assignment_37

- src/sayali/oopsinheritance/Assignment37_Employee.java
- src/sayali/oopsinheritance/Assignment37_Manager.java
> Sayali_Assignment_37

- src/jagrati/Assignment34.java
- src/jagrati/Assignment35.java
> Jagrati_Assignment_35

- src/gaurang/Assignment38.java
> Assignment_38

- src/gaurang/Assignment39.java
> Assignment_39

- src/gaurang/Assignment40.java
> Assignment_40

- src/gaurang/Assignment42.java
> Assignment_42

- src/gaurang/Assignment43.java
> Assignment_43

- src/denish/Assignment38.java
> Denish_Assignment_38

- src/denish/Assignment39.java
> Denish_Assignment_39

- src/hetal/Assignment42.java
> Hetal_Assignment42

- src/jagrati/Assignment41.java
> Jagrati_Assignment_41

- src/shrutika/CovertLowerToUpperA39.java
> Shrutika assignment 39

- src/hetal/Assignment43.java
> Hetal_Assignment_43

- src/shrutika/RepeatingVowelA40.java
> Shrutika_Assignment_40

- src/jaykumar/Assignment37_Employee.java
- src/jaykumar/Assignment37_InheritanceCases.java
- src/jaykumar/Assignment37_Manager.java
> Jaykumar_Assignment37

- src/shrutika/FirstVowelA41.java
> Shrutika_Assignment_41

- src/jaykumar/Assignment38.java
> Jaykumar_Assignment38

- src/jaykumar/Assignment39.java
> Jaykumar_Assignment39

- src/jaykumar/Assignment41.java
> Jaykumar_Assignment41

- src/aditya/String/Assinment21.java
> Aditya Assignment21

- src/sumeet/Assignment18.java
> Sumit_Assignment18: Sum and Average of number div by 5 & 7

- src/denish/Assignment41.java
> Denish_Assignment_41

- src/denish/Assignment42.java
> Denish_Assignment_42

- src/denish/Assignment43.java
> Denish_Assignment_43

- src/hetal/Assignment38.java
> Hetal_Assignment38

- src/swati/Ass38SumOfDigitsInString.java
> Swati_Assignment_38

- src/swati/Ass39CovertCase.java
> Swati_Assignment_39

- src/hetal/Assignment40.java
> Hetal_Assignment40

- src/swati/Ass41PrintStringFromFirstVowel.java
> Swati_Assignment_41

- src/swati/Ass42SumofDigitsOutsideString.java
> Swati_Assignment_42

- src/swati/Ass43DiffOfOuterSumToInnerSum.java
> Swati_Assignment_43

- src/narendra/oopsInheritance/CaseOutput.java
- src/narendra/oopsInheritance/Employee.java
- src/narendra/oopsInheritance/Manager.java
> Narendra-Assignment-37

- src/akshita/CaseConversion.java
Akshita_Assignment_39 Convert lowercase character to uppercase and vice versa
> Akshita_Assignment_39

- src/akshita/Vowels.java
Akshita assignment 38 Print sum of digit if there is any vowels in string
> Akshita assignment 38

- src/shrutika/InheritanceCasesA37.java
- src/shrutika/InheritanceCollegeA37.java
- src/shrutika/InheritanceStudentA37.java
> Shrutika_Assignment_37

- src/deepak/Assignment37_Employee.java
- src/deepak/Assignment37_InheritanceCases.java
- src/deepak/Assignment37_Manager.java
> Deepak_Assignment_37

- src/jagrati/Assignment38.java
> Jagrati_Assignment_38

- src/jagrati/Assignment39.java
> Jagrati_Assignment_39

- src/shrutika/SumofDigitA38.java
> Shrutika_Assignment_38

- src/jagrati/Assignment40.java
> Jagrati_Assignment_40

- src/aditya/Strings/Assignment23.java
Write a program to find count of Uppercase, lowercase, digits and special characters.
String str = "TecHNo_cR6ediTs";
output : Uppercase -> 5
Lowercase -> 8
Digit -> 1
Special char count -> 1
> Aditya_Assignment23

- src/mayank/Assignment36.java
> Assignment36

- src/shrutika/CalSumOfDigitA42.java
> Shrutika_Assignment_42

- src/sayali/Assignment40.java
> Sayali_Assignment_40

- src/sayali/Assignment41.java
> Sayali_Assignment_41

- src/sayali/Assignment42.java
> Sayali_Assignment_42

- src/aditya/Assignment24.java
- src/aditya/String/Assignment22.java
> Aditya Assignment24

- src/deepak/Assignment39_InvertCharacterCases.java
> Deepak_Assignment_39

- src/deepak/Assignment40_Substring1.java
> Deepak_Assignment_40

- src/deepak/Assignment41_Substring2.java
> Deepak_Assignment_41

- src/deepak/Assignment42_Substring3.java
> Deepak_Assignment_42

- src/akshita/SumNumoutsideVowels.java
Akshita_Assignment_42 sum of digits which are present outside of string having 1st and last repeating vowels of 'e'
> Akshita_Assignment_42

- src/akshita/DiffOuterInnerSum.java
Akshita_Assignment_43 difference of outer sum(t1dit983) and inner sum of (1st and last repeating vowels)
> Akshita_Assignment_43

- src/mayank/Assignment40.java
> Mayank_Assignment40

- src/mayank/Assignment41.java
> Mayank_Assignment41

- src/jaykumar/Assignment42.java
> Jaykumar_Assignment42

- src/sayali/Assignment43.java
> Sayali_Assignment_43

- src/pushpa/Assignment38.java
> Pushpa Assignment38

- src/pushpa/Assignment39.java
> Pushpa Assignment39

- src/pushpa/Assignment40.java
> Pushpa Assignment40

- src/pushpa/Assignment41.java
> Pushpa Assignment41

- src/pushpa/Assignment42.java
> Pushpa Assignment42

- src/pushpa/Assignment43.java
> Pushpa Assignment43

- src/jagrati/oops/inheritance/A.java
- src/jagrati/oops/inheritance/B.java
- src/jagrati/oops/inheritance/Test.java
> Jagrati_Assignment_37

- src/rahul/Assignment37_1_Case1.java
- src/rahul/Assignment37_1_Case2.java
- src/rahul/Assignment37_1_Case3.java
- src/rahul/Assignment37_1_Case4.java
- src/rahul/Assignment37_1_Case5.java
- src/rahul/Assignment37_1_Case6.java
- src/rahul/Assignment37_1_ClassA.java
- src/rahul/Assignment37_1_ClassB.java
> Rahul assignment 37

- src/gaurang/Assignment17.java
> Assignment_17

- src/jagrati/Assignment48.java
> Jagrati_Assignment_42

- src/yogesh/Yogesh_Assignment38.java
> Yogesh_Assignment38

- src/yogesh/Yogesh_Assignment39.java
> Yogesh_Assignment39

- src/yogesh/Yogesh_Assignment40.java
> Yogesh_Assignment40

- src/yogesh/Yogesh_Assignment41.java
> Yogesh_Assignment41

- src/yogesh/Yogesh_Assignment42.java
> Yogesh_Assignment42

- src/yogesh/Yogesh_Assignment43.java
> Yogesh_Assignment43

- src/jagrati/Assignment43.java
> Jagrati_Assignment_43

- src/mohit/Assignment_6.java
> Mohit_Assignment_6

- src/mohit/Assignment_7.java
> Mohit_Assignment_7

- src/mohit/Assignment_8.java
> Mohit_Assignment_8

- src/mohit/Assignment_9.java
> Mohit_Assignment_9

- src/jyoti/Assignment34.java
> Jyoti_Assignment34

- src/jyoti/Assignment35.java
> Jyoti_Assignment35

- src/jyoti/Assignment36.java
> Jyoti_Assignment36

- src/jyoti/Assignment38.java
> Jyoti_Assignment38

- src/jyoti/Assignment39.java
> Jyoti_Assignment39

- src/jyoti/Assignment40.java
> Jyoti_Assignment40

- src/jyoti/Assignment41.java
> Jyoti_Assignment41

- src/jyoti/Assignment42.java
> Jyoti_Assignment42

- src/jyoti/Assignment43.java
> Jyoti_Assignment43

- src/jyoti/Assignment37_All_InheritanceCases.java
> Jyoti_Assignment37_Inheritance

- src/rahul/Assignment38_1.java
> Rahul_Assignment-38

- src/rahul/Assignment39_1.java
> Rahul_Assignment-39

- src/rahul/Assignment40_1.java
> Rahul assignment 40

- src/akshita/AccessModifer/Employee.java
- src/akshita/AccessModifer/Manager.java
- src/akshita/Inheritance/A.java
- src/akshita/Inheritance/B.java
Akshita_Assignment_37  Assignment for Inheritance and Polymorphism with Access modifier
> Akshita_Assignment_37

- src/shamli/Assignment26.java
> Shamli_Assignment26

- src/shamli/Assignment27.java
> Shamli_Assignment27

- src/shamli/Assignment28.java
> Shamli_Assignment28

- src/shrutika/DiffInnerOuterSumA43.java
- src/shrutika/UpperCaseAssig30.java
> Shrutika_Assignment_43

- src/gaurang/Assignment44.java
> Gaurang_Assignment_44

- src/gaurang/Assignment45.java
> Gaurang_Assignment_45

- src/gaurang/Assignment46.java
> Gaurang_Assignment_46

- src/gaurang/Assignment47.java
> Gaurang_Assignment47

- src/gaurang/Assignment49.java
> Gaurang_Assignment_49

- src/onkar/Assignment39.java
> Onkar_Assignment39

- src/sayali/Assignment47.java
> Sayali_Assignment_47

- src/jagrati/Assignment50.java
> Jagrati_Assignment_50

- src/jaykumar/Assignment47.java
> Jaykumar_Assignment47

- src/onkar/Assignment40.java
> Onkar_Assignment40

- src/sayali/Assignment48.java
> Sayali_Assignment_48

- src/jaykumar/Assignment48.java
> Jaykumar_Assignment48

- src/onkar/Assignment41.java
> Onkar_Assignment41

- src/jaykumar/Assignment49.java
> Jaykumar_Assignment49

- src/sayali/Assignment49.java
> Sayali_Assignment_49

- src/onkar/Assignment42.java
> Onkar_Assignment42

- src/onkar/Assignment43.java
> Onkar_Assignmnet43

- src/aditya/String/Assignment25.java
> Aditya_Assignment25

- src/jaykumar/Assignment50.java
> Jaykumar_Assignment50

- src/roshani/Ass45MaxMinLenName.java
> Roshni_Assignment_45 : Print Name with Max and Min Length

- src/deepak/Assignment44_Array1.java
> Deepak_Assignment44

- src/deepak/Assignment45_Array2.java
> Deepak_Assignment45

- src/roshani/Ass46NameWithMaxDigitSum.java
> Roshni_Assignment_46 : Print Name With Max Digit Sum

- src/deepak/Assignment46_Array3.java
> Deepak_Assignment46

- src/deepak/Assignment47_Array4.java
> Deepak_Assignment47

- src/roshani/Ass47StringWithoutDigits.java
> Roshni_Assignment_47 : Print Name With Max digit Sum

- src/deepak/Assignment48_Array5.java
> Deepak_Assignment48

- src/gaurang/Assignment50.java
> Gaurang_Assignment_50

- src/shrutika/ArryUcaseA44.java
> Shrutika_Assignment_44

- src/denish/Assignment44.java
> Denish_Assignment_44

- src/denish/Assignment45.java
> Denish_Assignment_45

- src/denish/Assignment46.java
> Denish_Assignment_46

- src/denish/Assignment47.java
> Denish_Assignment_47

- src/denish/Assignment48.java
> Denish_Assignment_48

- src/denish/Assignment49.java
> Denish_Assignment_49

- src/swati/Ass45PrintStrHavMaxAndMinLen.java
> Swati_Assignment_45

- src/swati/Ass46PrintNameHavingMaxDigitSum.java
> Swati_Assignment_46

- src/hetal/Assignment44.java
> Hetal_Assignment44

- src/swati/Ass48ConvertCase.java
> Swati_Assignment_48

- src/shamli/Assignment31.java
> Shamli_Assignment31

- src/shamli/Assignment30.java
> Shamli new assignment30

- src/shamli/Assignment29.java
> Shamli_Assignment29

- src/shamli/Assignment30.java
> Shamli assignment30

- src/mohit/Assignment_18.java
> Mohit_Assignment_18

- src/mohit/Assignment_15.java
> Mohit_Assignment_15

- src/onkar/Assignment38.java
> Onkar_Assignment38

- src/rahul/Assignment41_1.java
> Rahul_Assignment-41

- src/hetal/Assignment45.java
> Hetal_Assignment45

- src/hetal/Assignment46.java
> Hetal_Assignment46

- src/swati/Ass50FindSecondMax.java
> Swati_Assignment_50

- src/pushpa/Assignment45.java
> Pushpa Assignment45

- src/pushpa/Assignment44.java
> Pushpa Assignment44

- src/pushpa/Assignment46.java
> Pushpa Assignment46

- src/pushpa/Assignment47.java
> Pushpa Assignment47

- src/pushpa/Assignment48.java
> Pushpa Assignment48

- src/pushpa/Assignment49.java
> Pushpa Assignment49

- src/pushpa/Assignment50.java
> Pushpa Assignment50

- src/jagrati/Assignment44.java
> Jagrati_Assignment_44

- src/hetal/Assignment48.java
> Hetal_Assignment48

- src/hetal/Assignment49.java
> Hetal_Assignment49

- src/jagrati/Assignment45.java
> Jagrati_Assignment_45

- src/jaykumar/Assignment44.java
> Jaykumar_Assignment44

- src/sayali/Assignment44.java
> Sayali_Assignment_44

- src/jagrati/Assignment46.java
> Jagrati_Assignment_46

- src/shrutika/ArryMinMaxLengthA45.java
> Shrutika_Assignment_45

- src/sayali/Assignment45.java
> Sayali_Assignment_45

- src/jagrati/Assignment47.java
> Jagrati_Assignment_48

- src/shrutika/ArrEliminateDigitA47.java
> Shrutika_Assignment_47

- src/shrutika/ArrEliminateDigitA47.java
- src/shrutika/ArryLowerToUpperA48.java
> Shrutika assignment 48

- src/jagrati/Assignment48_1.java
> Jagrati_Assignment48_1

- src/akshita/array/Assignment44.java
- src/akshita/array/DiffEvenOdd.java
- src/akshita/array/EvenUsingArray.java
- src/akshita/array/Name_FirstLetter.java
- src/akshita/array/SwapFirstLastofArray.java
Akshita_Assignment_44_ Convert input element into uppercase if it contain digit
I have done some Package path changes
> Akshita_Assignment_44_

- src/jaykumar/Assignment45.java
> Jaykumar_Assignment45

- src/rahul/Assignment42_1.java
> Rahul_Assignment-42

- src/shamli/Assignment38.java
> Shamli_Assignment38

- src/shamli/Assignment32.java
> Shamli_Assignment32

- src/jagrati/Assignment49.java
> Jagrati_Assignment_49

- src/sayali/Assignment46.java
> Sayali_Assignment_46

- src/jaykumar/Assignment46.java
> Jaykumar_Assignment46

- src/shrutika/ArrDiffYoungOldA49.java
> Shrutika_Assignment_49

- src/deepak/Assignment49_Array6.java
> Deepak_Assignment49

- src/deepak/Assignment50_Array7.java
> Deepak_Assignment50

- src/roshani/Ass49DiffInAge.java
> Roshni_Assignemnt_49 : Find diff in age

- src/shrutika/ArrySecondMaxNoA50.java
> Shrutika_Assignment_50

- src/akshita/array/Assignment_45.java
Akshita_Assignment_45  name having maximum and minimum length from given array
> Akshita_Assignment_45

- src/akshita/array/Assignment46.java
Akshita_Assignment_46  String having maximum digit sum
> Akshita_Assignment_46

- src/onkar/Assignment44.java
> Onkar_Assignment44

- src/onkar/Assignment45.java
> Onkar_Assignment45

- src/onkar/Assignment46.java
> Onkar_Assignment46

- src/onkar/Assignment47.java
> Onkar_Assignment47

- src/onkar/Assignment48.java
> Onkar_Assignment48

- src/sayali/Assignment50.java
> Sayali_Assignment_50

- src/onkar/Assignment49.java
> Onkar_Assignment49

- src/akshita/array/Assignment47.java
Akshita_Assignment_47 remove digit from given string and print
> Akshita_Assignment_47

- src/onkar/Assignment50.java
> Onkar_Assignment50

- src/array/Assignment48.java
Akshita_Assignment_48  convert element case from given array, Upper to Lower and Lower to upper
> Akshita_Assignment_48

- src/array/Assignment49.java
Akshita_Assignment_49 find the difference between age of youngest and lowest family member.
> Akshita_Assignment_49

- src/roshani/Assignment37_Employee.java
- src/roshani/Assignment37_Inheritance.java
- src/roshani/Assignment37_Manager.java
> Roshni_Assignment_37 : Inheritance

- src/nivedita/A41PrintFirst.java
> Nivedita_Assignment_41

- src/nivedita/A40PrintRep.java
> Nivedita_Assignment_40

- src/nivedita/A39ConvertChar.java
> Nivedita_Assignment_39

- src/nivedita/A42PrintSum.java
> Nivedita_Assignment_42

- src/nivedita/A43PrintDetails.java
> Nivedita_Assignment_43

- src/shamli/Assignment39.java
> Shamli_Assignment39

- src/aditya/String/Assignment26.java
> Aditya_Assignment26

- src/rahul/Assignment43_1.java
> Rahul_Assignment-43

- src/yogesh/Yogesh_Assignment44.java
> Yogesh_Assignment44

- src/yogesh/Yogesh_Assignment45.java
> Yogesh_Assignment45

- src/yogesh/Yogesh_Assignment46.java
> Yogesh_Assignment46

- src/yogesh/Yogesh_Assignment47.java
> Yogesh_Assignment47

- src/yogesh/Yogesh_Assignment48.java
> Yogesh_Assignment48

- src/yogesh/Yogesh_Assignment49.java
> Yogesh_Assignment49

- src/yogesh/Yogesh_Assignment50.java
> Yogesh_Assignment50

- src/shamli/Assignment40.java
> Shamli_Assignment40

- src/shamli/Assignment41.java
> Shamli_Assignment41

- src/shamli/Assignment42.java
> Shamli_Assignment42

- src/akshita/array/Assignment48.java
- src/akshita/array/Assignment49.java
- src/akshita/array/Assignment50.java
Akshita_Assignent_50  Find second max from given array and did some file path changes
> Akshita_Assignent_50

- src/shamli/Assignment43.java
> Shamli_Assignment43

- src/shamli/array/Assignment44.java
> Shamli_Assignment44

- src/gaurang/Assignment55.java
> Gaurang_Assignment55

- src/gaurang/Assignment51.java
> Assignment_51

- src/gaurang/Assignment52.java
> Assignment_52

- src/gaurang/Assignment26.java
> Assignment_26

- src/gaurang/Assignment27.java
> Assignment_27

- src/gaurang/Assignment28.java
> Assignment_28

- src/gaurang/Assignment29.java
> Assignment_29

- src/gaurang/Assignment30.java
> Assignment_30

- src/gaurang/Assignment31.java
> Assignment_31

- src/gaurang/Assignment32.java
> Assignment_32
