src/gaurang/Assignment33.java
=> Assignment_33

src/gaurang/Assignment34.java
=> Assignment_34

src/gaurang/Assignment35.java
=> Assignment_35

src/gaurang/Assignment36.java
=> Assignment_36

src/swati/Ass51PrintVowelFromStringArray.java
=> Swati_Assignment_51

src/gaurang/Assignment53.java
=> Assignment_53

src/gaurang/Assignment54.java
=> Assignment_54

src/swati/Ass52PrintCountOfVowels.java
=> Swati_Assignment_52

src/gaurang/Assignment56.java
=> Assignment_56

src/swati/Ass53ReturnUniqueVowel.java
=> Swati_Assignment_53

src/swati/Ass55PrintVowelsInArrayOfString.java
=> Swati_Assignment_55

src/swati/Ass55PrintVowelsInArrayOfString.java
=> Swati_Assignment_56

src/swati/Ass54PrintNotrepetingvowel.java
=> Swati_Assignment54

src/swati/Ass56PrintLonestStringVowels.java
=> Swati assignment56

src/subramanian/Assignment25.java
=> Subramanian_Assignment_25

src/denish/Assignment51.java
=> Denish_Assignment_51

src/denish/Assignment52.java
=> Denish_Assignment_52

src/onkar/Assignment51.java
=> Onkar_Assignment51

src/denish/Assignment53.java
=> Denish_Assignment_53

src/denish/Assignment54.java
=> Denish-Assignment_54

src/denish/Assignment55.java
=> Denish_assignment_55

src/shrutika/StringVowelA51.java
=> Shrutika assignment 51

src/onkar/Assignment52.java
=> Onkar_Assignment52

src/onkar/Assignment53.java
=> Onkar_Assignment53

src/onkar/Assignment54.java
=> Onkar_Assignment54

src/onkar/Assignment55.java
=> Onkar_Assignment55

src/onkar/Assignment56.java
=> Onkar_Assignment56

src/subramanian/Assignment34.java
=> Subramanian_Assignment_34

src/onkar/Assignment58.java
=> Onkar_Assignment58

src/shrutika/StringVowelCntA52.java
=> Shrutika_Assignment_52

src/denish/Assignment56.java
=> Denish_Assignment_56

src/onkar/Assignment57.java
=> Onkar_Assignment57

src/akshita/String/Assignment51.java
Akshita_Assignment_51 WAP to write vowels from string
=> Akshita assignment 51

src/denish/Assignment57.java
=> Denish_Assignment_57

src/denish/Assignment58.java
=> Denish_Assignment_58

src/array/Assignment52.java
Akshita_Assignment_52 print count of vowels
=> Akshita_Assignment_52

src/shrutika/ReturnUniqVowelA53.java
=> Shrutika_Assignment_53

src/array/Assignment53.java
Akshita_Assignment_53 return unique vowels from string
=> Akshita_Assignment_53

src/pushpa/Assignment52.java
=> Pushpa Assignment52

src/pushpa/Assignment53.java
=> Pushpa Assignment53

src/pushpa/Assignment54.java
=> Pushpa Assignment54

src/pushpa/Assignment56.java
=> Pushpa Assignment56

src/pushpa/Assignment51.java
=> Pushpa Assignment51

src/shrutika/As54NonrepetiveVowel.java
=> Shrutika assignment 54

src/jyoti_Array/Assignment44.java
=> Jyoti_Assignment44

src/jyoti_Array/Assignment44.java, src/jyoti_Array/Assignment45.java
=> Jyoti assignment45

src/jyoti_Array/Assignment44.java, src/jyoti_Array/Assignment45.java, src/jyoti_Array/Assignment46.java
=> Jyoti assignment46

src/jyoti_Array/Assignment44.java, src/jyoti_Array/Assignment45.java, src/jyoti_Array/Assignment46.java, src/jyoti_Array/Assignment47.java
=> Jyoti assignment47

src/jyoti_Array/Assignment44.java, src/jyoti_Array/Assignment45.java, src/jyoti_Array/Assignment46.java, src/jyoti_Array/Assignment47.java, src/jyoti_Array/Assignment48.java
=> Jyoti assignment48

src/jyoti_Array/Assignment44.java, src/jyoti_Array/Assignment45.java, src/jyoti_Array/Assignment46.java, src/jyoti_Array/Assignment47.java, src/jyoti_Array/Assignment48.java, src/jyoti_Array/Assignment49.java
=> Jyoti assignment49

src/jyoti_Array/Assignment44.java, src/jyoti_Array/Assignment45.java, src/jyoti_Array/Assignment46.java, src/jyoti_Array/Assignment47.java, src/jyoti_Array/Assignment48.java, src/jyoti_Array/Assignment49.java, src/jyoti_Array/Assignment50.java
=> Jyoti assignment50

src/deepak/Assignment51_GetVowels.java
=> Deepak assignment51

src/deepak/Assignment52_GetVowelCount.java
=> Deepak_Assignment52

src/deepak/Assignment53_GetUniqueVowels.java
=> Deepak_Assignment53

src/deepak/Assignment54_GetUniqueNonRepVowels.java
=> Deepak_Assignment54

src/deepak/Assignment55_GetVowelsArray1.java
=> Deepak_Assignment55

src/deepak/Assignment56_GetVowelsArray2.java
=> Deepak_Assignment56

src/deepak/Assignment57_GetVowelConsonants.java
=> Deepak_Assignment57

src/deepak/Assignment58_SpecialChars.java
=> Deepak_Assignment58

src/rahul/Assignment44_1.java
=> Rahul assignment 44

src/gaurang/Assignment57.java
=> Assignment_57

src/gaurang/Assignment58.java
=> Assignment_58

src/pushpa/Assignment57.java
=> Pushpa Assignment57

src/pushpa/Assignment58.java
=> Pushpa Assignment58

src/shamli/stringprograms/Assignment52.java, src/shamli/stringprograms/Assignment52VowelCount.java
=> Shamli_Assignment52

src/nivedita/A45PrintMaxMinLength.java
=> Nivedita_Assignment_45

src/nivedita/A48ConvertCase.java
=> Nivedita_Assignment_48

src/nivedita/A47ReturnArr.java
=> Nivedita_Assignment_47

src/nivedita/A49DiffAge.java
=> Nivedita_Assignment_49

src/nivedita/A44ConvertUpper.java
=> Nivedita_Assignment_44

src/nivedita/A46PrintSum.java
=> Nivedita_Assignment_46

src/nivedita/A50FindSecondMax.java
=> Nivedita_Assignment_50

src/sayali/Assignment51.java
=> Sayali_Assignment_51

src/sayali/Assignment52.java
=> Sayali_Assignment_52

src/sayali/Assignment53.java
=> Sayali_Assignment_53

src/sayali/Assignment54.java
=> Sayali_Assignment_54

src/sayali/Assignment55.java
=> Sayali_Assignment_55

src/shamli/Assignment51.java
=> Shamli_Assignment51

src/sayali/Assignment56.java
=> Sayali_Assignment_56

src/nivedita/A51PrintVowel.java
=> Nivedita_Assignment_51

src/nivedita/A54PrintVowel.java
=> Nivedita_Assignment_54

src/nivedita/A55PrintArray.java
=> Nivedita_Assignment_55

src/nivedita/A52PrintCount.java
=> Nivedita_Assignment_52

src/nivedita/A53ReturnVowel.java
=> Nivedita_Assignment_53

src/nivedita/A56PrintVowels.java
=> Nivedita_Assignment_56

src/sayali/Assignment57.java
=> Sayali assignment57

src/sayali/Assignment58.java
=> Sayali_Assignment_58

src/shrutika/ArryA55.java
=> Shrutika_Assignment_55

src/jaykumar/Assignment51.java
=> Jaykumar_Assignment51

src/jaykumar/Assignment52.java
=> Jaykumar_Assignment52

src/shamli/Assignment53.java
=> Shamli_Assignment53

src/jaykumar/Assignment53.java
=> Jaykumar_Assignment53

src/Jyoti_Practice/Assignment51.java
=> Jyoti_Assignment51

src/Jyoti_Practice/Assignment58.java
=> Jyoti_Assignment58

src/jaykumar/Assignment54.java
=> Jaykumar_Assignment54

src/Jyoti_Practice/Assignment57.java
=> Jyoti_Assignment57

src/Jyoti_Practice/Assignment56.java
=> Jyoti_Assignment56

src/Jyoti_Practice/Assignment55.java
=> Jyoti_Assignment55

src/jaykumar/Assignment55.java
=> Jaykumar_Assignment55

src/Jyoti_Practice/Assignment54.java
=> Jyoti_Assignment54

src/Jyoti_Practice/Assignment53.java
=> Jyoti_Assignment53

src/Jyoti_Practice/Assignment52.java
=> Jyoti_Assignment52

src/shamli/Assignment54.java
=> Shamli_Assignment54

src/jaykumar/Assignment56.java
Jaykumar_Assignment56:
nment56
=> Jaykumar_Assignment56

src/jaykumar/Assignment57.java
=> Jaykumar_Assignment57

src/shamli/array/Assignment55.java
=> Shamli_Assignment55

src/jaykumar/Assignment58.java
=> Jaykumar_Assignment58

src/shamli/array/Assignment56.java
=> Shamli_Assignment56

src/shamli/stringprograms/Assignment57.java
=> Shamli_Assignment57

src/shamli/stringprograms/Assignment58.java
=> Shamli_Assignment58

src/shamli/array/Assignment45.java
=> Shamli_Assignment45

src/swati/Ass57PrintConsonantsInString.java
=> Swati_Assignment_57

src/swati/Ass58PrintOnlySpecialChar.java
=> Swati_Assignment_58

src/hetal/Assignment25.java
=> Hetal_Assignment25

src/shamli/array/Assignment46.java
=> Shamli_Assignment46

src/shamli/array/Assignment48.java
=> Shamli_Assignment48

src/shamli/array/Assignment49.java
=> Shamli_Assignment49

src/hetal/Assignment50.java
=> Hetal_Assignment50

src/shamli/array/Assignment50.java
=> Shamli assignment50

src/hetal/Assignment51.java
=> Hetal_Assignment51

src/hetal/Assignment52.java
=> Hetal_Assignment52

src/hetal/Assignment53.java
=> Hetal_Assignment53

src/hetal/Assignment54.java
=> Hetal_Assignment54

src/array/Assignment54.java
Akshita_Assignment54 Return non repetitive vowels from string
=> Akshita_Assignment54

src/akshita/array/Assignment55.java
Akshita_Assignment_55 vowels of each string from given string array
=> Akshita_Assignment_55

src/akshita/array/Assignment56.java
Akshita_Assignment_56  print vowels if count is greater than 2
=> Akshita_Assignment_56

src/sakshi/Assignment30.java
=> sakshi_Assignment30

src/sakshi/Assignment31.java
=> sakshi_Assignment31

src/sakshi/Assignment32.java
=> sakshi_Assignment32

src/sakshi/Assignment35.java
=> sakshi_Assignment35

src/sakshi/Assignment36.java
=> sakshi_Assignment36

src/sakshi/oops/inheritance/Client.java, src/sakshi/oops/inheritance/Employee.java, src/sakshi/oops/inheritance/Manager.java
=> sakshi_Assignment37

src/hetal/Assignment55.java
=> Hetal_Assignment55

src/hetal/Assignment56.java
=> Hetal_Assignment56

src/hetal/Assignment58.java
=> Hetal_Assignment58

src/akshita/array/Assignment57.java
Akshita_Assignment_57  print consonants from given string and count of consonant and vowels from given string
=> Akshita_Assignment_57

src/akshita/array/Assignment58.java
Akshita_Assignment_58 print special character from given string
=> Akshita_Assignment_58

src/shrutika/ArryA56.java
=> Shrutika_Assignment_56

src/rahul/Assignment46_1.java
=> Rahul_Assignment-46

src/rahul/Assignment47_1.java
=> Rahul_Assignment-47

src/roshani/Ass39ConvertCase.java
=> Roshni_Assignment_39 : Convert case

src/roshani/Ass40PrintString.java
=> Roshni_Assignment_40 : Print String from 1st to last repeatating vowel

src/roshani/Ass38SumDigitsIfVowels.java
=> Roshni_Assignment_38 : Sum of digits in string only if having vowels

src/shrutika/As57StringConsonant.java
=> Shrutika assignment 57

src/shrutika/As58StringSpeiclChar.java
=> Shrutika_Assignment_58

src/roshani/Ass55VowelsOfEachString.java
=> Roshni_Assignment_55: Print vowels

src/roshani/Ass56VowelsCountGreater2.java
=> Roshni_Assignment_56 : Print Vowels only if count > 2

src/roshani/Ass57ConsonantsVowelsCount.java
=> Roshni_Assignment_57: Print Consonant Vowels Count

src/roshani/Ass58SpecialChar.java
=> Roshni_Assignment_58 : Print Special Char

src/roshani/Ass51PrintVowels.java
=> Roshni_Assignment_58 : Print Vowels in string

src/roshani/Ass52CountVowelsInString.java
=> Roshni_Assignment_52:Print count of vowels

src/roshani/Ass53ReturnUniqueVowels.java
=> Roshni_Assignment_53 : Return unique vowels

src/roshani/Ass54UniqueVowels.java
=> Roshni_Assignment_54: Unique non-repeated vowels

src/yogesh/Yogesh_Assignment51.java
=> Yogesh_Assignment51

src/yogesh/Yogesh_Assignment51.java, src/yogesh/Yogesh_Assignment52.java
=> Yogesh assignment52

src/yogesh/Yogesh_Assignment53.java
=> Yogesh_Assignment53

src/yogesh/Yogesh_Assignment54.java
=> Yogesh_Assignment54

src/yogesh/Yogesh_Assignment55.java
=> Yogesh_Assignment55

src/yogesh/Yogesh_Assignment56.java
=> Yogesh_Assignment56

src/roshani/Ass41StringFromFirstVowel.java
=> Roshni_Assignment_41:Print string from first vowel

src/roshani/Ass42SumofDigit.java
=> Roshni_Assignment_42: Sum of Digits

src/roshani/Assignment43.java
=> Roshni_Assignment_43

src/sakshi/Assignment44.java
=> Sakshi_Assignment44

src/sakshi/Assignment45.java
=> Sakshi_Assignment45

src/sakshi/Assignment46.java
=> Sakshi_Assignment46

src/sakshi/Assignment47.java
=> Sakshi_Assignment47

src/sakshi/Assignment38.java
=> Sakshi_Assignment38

src/sakshi/Assignment39.java
=> Sakshi_Assignment39

src/jagrati/Assignment51.java
=> Jagrati_Assignment_51

src/jagrati/Assignment52.java
=> Jagrati_Assignment_52

src/jagrati/Assignment53.java
=> Jagrati_Assignment_53

src/jagrati/Assigment54.java
=> Jagrati_Assignment_54

src/jagrati/Assignment55.java
=> Jagrati_Assignment_55

src/jagrati/Assignment56.java
=> Jagrati_Assignment_56

src/jagrati/Assignment57.java
=> Jagrati_Assignment_57

src/jagrati/Assignment58.java
=> Jagrati_Assignment_58

src/rahul/Assignment48_1.java
=> Rahul_Assignment-48

src/akshita/keyword/KeySuper.java, src/akshita/keyword/KeyThis.java
=> keywords_Super_This

src/rahul/Assignment49_1.java
=> Rahul_Assignment-49

src/jaykumar/Assignment59.java
=> Jaykumar_Assignment59

src/jaykumar/Assignment60.java
=> Jaykumar_Assignment60

src/jaykumar/Assignment61.java
=> Jaykumar_Assignment61

src/jaykumar/Assignment62.java
=> Jaykumar_Assignment62

src/akshita/array/Asignment59.java
Akshita assignment 59 Calculator by taking run time input
=> Akshita assignment 59

src/swati/Ass59CalcutorUSingScanner.java
Output 1 : Addition
Output 2 : Division and Subtraction
Output 3 : Multiplication
=> Swati_Assignment_59

src/akshita/array/Assignment60.java
Akshita_Assignment_60 Using scanner class, print digit sum of each name.
=> Akshita_Assignment_60

src/roshani/Ass59Calculator.java
=> Roshni_Assignment_59

src/rahul/Assignment50_1.java
=> Rahul assignment 50

src/rahul/Assignment51_1.java
=> Rahul_Assignment-50

src/rahul/Assignment52_1.java
=> Rahul_Assignment-52

src/rahul/Assignment53_1.java
=> Rahul_Assignment-53

src/jaykumar/Assignment63.java
=> Jaykumar_Assignment63

src/roshani/Ass60DigitSum.java
=> Roshni_Assignment_60 : Digit Sum using scanner class

src/roshani/Ass61NumberCheckUsingScanner.java
=> Roshni_Assignment_61 : Take 2 valid numbers from user using scannerclass

src/denish/Assignment59.java
=> Denish_Assignment_59

src/denish/Assignment60.java
=> Denish_Assignment_60

src/denish/Assignment61.java
=> Denish_Assignment_61

src/denish/Assignment62.java
=> Denish_Assignment_62

src/denish/Assignment63.java
=> Denish_Assignment_63

src/akshita/array/Assignment61.java
Akshita_Assignment_61 Take 2 valid numbers from user using scanner class and use exception handling mechanism.
=> Akshita_Assignment_61

src/roshani/Assignment62.java
=> Roshni_Assignment_62 : DigitSum in given string using exception

src/swati/Ass60PrintSumUsingScanner.java
=> Swati_Assignment_60

src/swati/Ass61ScannerExceptionHandling.java
=> Swati_Assignment_61

src/swati/Ass62UseScannerAndExceptionHanding.java
=> Swati_Assignment_62

src/sayali/Assignment59.java
=> Sayali_Assignment_59

src/sayali/Assignment60.java
=> Sayali_Assignment_60

src/sayali/Assignment61.java
=> Sayali_Assignment_61

src/yogesh/Yogesh_Assignment57.java
=> Yogesh_Assignment57

src/yogesh/Yogesh_Assignment58.java
=> Yogesh_Assignment58

src/yogesh/Yogesh_Assignment59.java
=> Yogesh_Assignment59

src/yogesh/Yogesh_Assignment60.java
=> Yogesh_Assignment60

src/yogesh/Yogesh_Assignment61.java
=> Yogesh_Assignment61

src/shrutika/As30UpperCase.java, src/shrutika/As31Ascii.java, src/shrutika/As32AsciiValues.java, src/shrutika/As33ArryEvenNum.java, src/shrutika/As34PositiveSum.java, src/shrutika/As35ArryFirstLetterOfArry.java, src/shrutika/As36ArrySwap.java, src/shrutika/As37InheritanceCases.java, src/shrutika/As37InheritanceCollege.java, src/shrutika/As37InheritanceStudent.java, src/shrutika/As38SumofDigit.java, src/shrutika/As39CovertLowerToUpper.java, src/shrutika/As40RepeatingVowel.java, src/shrutika/As41FirstVowel.java, src/shrutika/As42CalSumOfDigit.java, src/shrutika/As43DiffInnerOuterSum.java, src/shrutika/As44ArryUcase.java, src/shrutika/As45ArryMinMaxLength.java, src/shrutika/As46ArryMaxDigitSum.java, src/shrutika/As47ArrEliminateDigit.java, src/shrutika/As48ArryLowerToUpper.java, src/shrutika/As49ArrDiffYoungOld.java, src/shrutika/As50ArrySecondMaxNo.java, src/shrutika/As51StringVowel.java, src/shrutika/As52StringVowelCnt.java, src/shrutika/As53ReturnUniqVowel.java, src/shrutika/As55Arry.java, src/shrutika/As56Arry.java, src/shrutika/As59ScannerCalculator.java
=> Shrutika_Assignment_59

src/shrutika/As60ScannerStringDigit.java
=> Shrutika_Assignment_60

src/mohit/Assignment_54.java
=> Mohit_Assignment_54

src/mohit/Assignment_53.java
=> Mohit_Assignment_53

src/mohit/Assignment_55.java
=> Mohit_Assignment_55

src/mohit/Assignment_51.java
=> Mohit_Assignment_51

src/mohit/Assignment_52.java
=> Mohit_Assignment_52

src/mohit/Assignment_57.java
=> Mohit_Assignment_57

src/mohit/Assignment_58.java
=> Mohit_Assignment_58

src/pavan/Assi26.java
=> Assignemnt_26_pavanChadhari

src/pavan/Assi27.java
=> Assignment27_pavan

src/pavan/Assi28.java
=> Assignment28_pavan

src/yogesh/Yogesh_Assignment62.java
=> Yogesh_Assignment62

src/yogesh/Yogesh_Assignment63.java
=> Yogesh_Assignment63

src/onkar/Assignment60.java
=> Onkar_Assignment60

src/jaykumar/Assignment65.java
=> Jaykumar_Assignment65

src/denish/Assignment65.java
=> Denish_Assignment_65

src/shrutika/As61ScannerWithException.java
=> Shrutika_Assignment_61

src/hetal/Assignment60.java
=> Hetal_Assignment60

src/jyoti_scanner_exception/Assignment59.java
=> Jyoti_Assignment59

src/jyoti_scanner_exception/Assignment59.java, src/jyoti_scanner_exception/Assignment60.java
=> Jyoti assignment60

src/gaurang/Assignment59.java
=> Assignment_59

src/shrutika/As62ExceptionHandling.java
=> Shrutika_Assignment_62

src/hetal/Assignment61.java
=> Hetal_Assignment61

src/gaurang/Assignment60.java
=> Assignment_60

src/hetal/Assignment62.java
=> Hetal_Assignment62

src/shrutika/As63PrimeNumer.java
=> Shrutika assignment 63

src/swati/Ass63PrimeNumber.java
=> Swati_Assignment_63

src/shrutika/As63Armstrong.java
=> Shrutika_Assignment_64

src/mohit/Assignment_38.java
=> Mohit_Assignment_38

src/mohit/Assignment_39.java
=> Mohit_Assignment_39

src/mohit/Assignment_40.java
=> Mohit_Assignment_40

src/mohit/Assignment_41.java
=> Mohit_Assignment_41

src/mohit/Assignment_42.java
=> Mohit_Assignment_42

src/mohit/Assignment_43.java
=> Mohit_Assignment_43

src/mohit/Assignment_48.java
=> Mohit_Assignment_48

src/mohit/Assignment_56.java
=> Mohit assignment 56

src/jyoti_scanner_exception/Assignment59.java, src/jyoti_scanner_exception/Assignment60.java, src/jyoti_scanner_exception/Assignment61.java, src/jyoti_scanner_exception/Assignment62.java, src/jyoti_scanner_exception/Assignment63.java
=> Jyoti assignment63

src/swati/Ass65FindPalindromeNumber.java
=> Swati_Assignment_65

src/akshita/array/Assignment63.java
Akshita_Assignment_63 Count the prime number in range of 50 to 150
=> Akshita_Assignment_63

src/swati/Ass64ArmstrongNumber.java
=> Swati_Assignment_64

src/nivedita/A61ExcepHandling.java
=> Nivedita_Assignment_61

src/nivedita/A59CalMethod.java
=> Nivedita_Assignment_59

src/pratik/Assignment51.java
=> Pratik_Assignment51

src/pratik/Assignment52.java
=> Pratik_Assignment52

src/pratik/Assignment53.java
=> Pratik_Assignment53

src/sayali/Assignment64.java
=> Sayali_Assignment_64

src/shrutika/As64Armstrong.java, src/shrutika/As65Palindrom.java
=> Shrutika_Assignment_65

src/sayali/Assignment65.java
=> Sayali_Assignment_65

src/akshita/array/Assignment65.java
Akshita_Assignment_65   alphanumeric string palindrome
=> Akshita_Assignment_65

src/jyoti_scanner_exception/Assignment65.java
=> Jyoti_Assignment65

src/jyoti_scanner_exception/Assignment64.java
=> Jyoti_Assignment64

src/roshani/Ass63PrimeNumber.java
=> Roshni_Assignment_63 : Prime Numbers

src/roshani/Ass64ArmstrongNum.java
=> Roshni_Assignment_64 : Armstrong Num

src/roshani/Ass65PalindromeNum.java
=> Roshni_Assignment_65 : Palindrome

src/deepak/Assignment59_ScannerCalculator.java
=> Deepak_Assignment59

src/deepak/Assignment60_ScannerDigitSum.java
=> Deepak_Assignment60

src/deepak/Assignment61_ScannerCalculatorValidNum.java
=> Deepak_Assignment61

src/deepak/Assignment62_ScannerSumUsingExcptnHandling.java
=> Deepak_Assignment62

src/jaykumar/Assignment66.java
=> Jaykumar_Assignment66

src/jaykumar/Assignment67.java
=> Jaykumar_Assignment67

src/swati/Ass66ReverseNumber.java
=> Swati_Assignment_66

src/roshani/Ass66ReverseNum.java
=> Roshni_Assignment_66: ReverseNum

src/sayali/Assignment66.java
=> Sayali_Assignment_66

src/jyoti_scanner_exception/Assignment66.java
=> Jyoti_Assignment66

src/jyoti_scanner_exception/Assignment67.java
=> Jyoti_Assignment67

src/roshani/Ass67TernaryOp.java
=> Roshni_Assignment_67 : TernaryOperator

src/swati/Ass67TernaryOperator.java
=> Swati_Assignment_67

src/yogesh/Yogesh_Assignment64.java
=> Yogesh_Assignment64

src/yogesh/Yogesh_Assignment65.java
=> Yogesh_Assignment65

src/yogesh/Yogesh_Assignment66.java
=> Yogesh_Assignment66

src/yogesh/Yogesh_Assignment67.java
=> Yogesh_Assignment67

src/denish/Assignment66.java
=> Denish_Assignment_66

src/denish/Assignment67.java
=> Denish_Assignment_67

src/jyoti_scanner_exception/Assignment66_1.java
=> Jyoti_Assignment66_WithCorrection

src/roshani/Ass68SingletonDesignClient.java, src/roshani/Ass68SingletonDesignConnection.java
=> Roshni_Assignment_68:SingletonDesign Pattern

src/onkar/Assignment61.java
=> Onkar_Assignment61

src/sayali/Ass68Client.java, src/sayali/Assignment68Connection.java
=> Sayali_Assignment_68_SingletonDP

src/onkar/Assignment62.java
=> Onkar_Assignment62

src/sayali/Assignment69.java
=> Sayali_Assignment_69

src/denish/Assignment68SingletonDesignClient.java, src/denish/Assignment68SingletonDesignConnection.java
=> Denish_Assignment_68

src/denish/Assignment69.java
=> Denish_Assignment_69

src/Jyoti_Misc/Assignment69.java
=> Jyoti_Assignment69

src/Jyoti_Misc/Assignment68_Client.java, src/Jyoti_Misc/Assignment68_Connection.java
=> Jyoti_Assignment68_SingeltonPattern

src/roshani/Ass69SwitchCase.java
=> Roshni_Assignment_69 : Switch Case

src/onkar/Assignment63.java
=> Onkar_Assignment63

src/onkar/Assignment64.java
=> Onkar_Assignment64

src/onkar/Assignment65.java
=> Onkar_Assignment65

src/onkar/Assignment66.java
=> Onkar_Assignment66

src/onkar/Assignment67.java
=> Onkar_Assignment67

src/onkar/Assignment68/Client.java, src/onkar/Assignment68/SingletoneDesignPattern.java
=> Onkar_Assignment68

src/onkar/Assignment69.java
=> Onkar_Assignment69

src/akshita/array/Assignent66.java
Akshita_Assignment_66 Return number in reverse order
=> Akshita_Assignment_66

src/akshita/array/Assignment67.java
Akshita-Assignment_67 using ternary operator WAP to return operation code
=> Akshita-Assignment_67

src/jaykumar/Assignment68_Client.java, src/jaykumar/Assignment68_Connection.java
=> Jaykumar_Assignment68

src/jaykumar/Assignment69.java
=> Jaykumar_Assignment69

src/yogesh/SingletonClient.java, src/yogesh/Yogesh_Assignment68.java
=> Yogesh_Assignment68

src/yogesh/Yogesh_Assignment69.java
=> Yogesh_Assignment69

src/deepak/Assignment70_UniqueNamesArrayList.java
=> Assignment70_Deepak

src/deepak/Assignment71_GetUniqueNameArrayList.java
=> Assignment71_Deepak

src/deepak/Assignment72_DuplicateNamesArrayList.java
=> Assignment72_Deepak

src/deepak/Assignment73_Insert100AtNegativeNumIndex.java
=> Assignment73_Deepak

src/deepak/Assignment74_PrimeNumList.java
=> Assignment74_Deepak

src/denish/Assignment70.java
=> Denish_Assignment_70

src/denish/Assignment71.java
=> Denish_Assignment_71

src/denish/Assignment72.java
=> Denish_Assignment_72

src/denish/Assignment73.java
=> Denish_Assignment_73

src/aditya/Collection/Assignment70.java
=> Aditya_Assignment_70

src/sayali/Assignment70.java
=> Sayali_Assignment_70

src/sayali/Assignment71.java
=> Sayali_Assignment_71

src/sayali/Assignment73.java
=> Sayali_Assignment_73

src/sayali/Assignment74.java
=> Sayali_Assignment_74

src/pushpa/Assignment59.java
=> Pushpa Assignment59

src/pushpa/Assignment60.java
=> Pushpa Assignment60

src/pushpa/Assignment61.java
=> Pushpa_Assignment61

src/pushpa/Assignment62.java
=> Pushpa Assignment62

src/pushpa/Assignment64.java
=> Pushpa Assignment64

src/pushpa/Assignment63.java
=> Pushpa Assignment63

src/pushpa/Assignment65.java
=> Pushpa Assignment65

src/sakshi/Assignment51.java
=> Sakshi_Assignment51

src/sakshi/Assignment52.java
=> Sakshi_Assignment52

src/sakshi/Assignment54.java
=> Sakshi_Assignment_54

src/sakshi/Assignment53.java
=> Sakshi_Assignment53

src/swati/Ass68ClientClass.java, src/swati/Ass68SingleTonDesignPattern.java
=> Swati_Assignment_68

src/sakshi/Assignment55.java
=> Sakshi_Assignment_55

src/sakshi/Assignment70.java
=> Sakshi_Assignment_70

src/sakshi/Assignment71.java
=> Sakshi_Assignment_71

src/swati/Ass69UseSwitchCase.java
=> Swati_Assignment_69

src/pushpa/Assignment66.java
=> Pushpa_Assignment66

src/pushpa/Assignment67.java
=> Pushpa Assignment67

src/sakshi/Assignment72.java
=> Sakshi_Assignment_72

src/sakshi/Assignment73.java
=> Sakshi_Assignment_73

src/sakshi/Assignment74.java
=> Sakshi_Assignment_74

src/roshani/Ass70UniqueNamesArrayList.java
=> Roshni_Assignment_70

src/yogesh/Yogesh_Assignment75.java, src/yogesh/Yogesh_Assignment76.java, src/yogesh/Yogesh_Assignment77.java
=> Yogesh assignment77

src/yogesh/Yogesh_Assignment75.java
=> Yogesh_Assignment75

src/yogesh/Yogesh_Assignment75.java, src/yogesh/Yogesh_Assignment76.java
=> Yogesh assignment76

src/gaurang/Assignment70.java
=> Assignment_70

src/gaurang/Assignment71.java
=> Assignment_71

src/gaurang/Assignment73.java
=> Assignment_73

src/onkar/Assignment70.java
=> Onkar_Assignment70

src/gaurang/Assignment74.java
=> Assignment_74

src/onkar/Assignment71.java
=> Onkar_Assignment71

src/gaurang/Assignment75.java
=> Assignment_75

src/yogesh/Yogesh_Assignment74.java
=> Yogesh_Assignment74

src/gaurang/Assignment76.java
=> Assignment_76

src/yogesh/Yogesh_Assignment72.java
=> Yogesh_Assignment72

src/yogesh/Yogesh_Assignment70.java
=> Yogesh_Assignment70

src/yogesh/Yogesh_Assignment71.java
=> Yogesh_Assignment71

src/jaykumar/Assignment70.java
=> Jaykumar_Assignment70

src/jaykumar/Assignment71.java
=> Jaykumar_Assignment71

src/onkar/Assignment72.java
=> Onkar_Assignment72

src/jaykumar/Assignment72.java
=> Jaykumar_Assignment72

src/jaykumar/Assignment73.java
=> Jaykumar_Assignment73

src/onkar/Assignment73.java
=> Onkar_Assignment73

src/onkar/Assignment74.java
=> Onkar_Assignment74

src/yogesh/Yogesh_Assignment78.java
=> Yogesh_Assignment78

src/jaykumar/Assignment74.java
=> Jaykumar_Assignment74

src/yogesh/Yogesh_Assignment75.java, src/yogesh/Yogesh_Assignment76.java
hi
Sorry, please neglect as I had error mentionrd in skype
=> Yogesh_Assignment76

src/jaykumar/Assignment75.java
=> Jaykumar_Assignment75

src/jaykumar/Assignment78.java
=> Jaykumar_Assignment78

src/onkar/Assignment75.java
=> Onkar_Assignment75

src/jaykumar/Assignment77.java
=> Jaykumar_Assignment77

src/akshita/array/Assignment69.java
Akshita_Assignment69 Find weekdays or weekends based on day Index using switch case.
=> Akshita_Assignment69

src/jaykumar/Assignment76.java
=> Jaykumar Assignment76

src/akshita/collection/Assignment72.java
Akshita_Assignment_72 Return list of names having frequency more than 1 from given ArrayList
=> Akshita_Assignment_72

src/roshani/Assignment78.java
=> Roshni_Assignment_78

src/sakshi/Assignment78.java
=> Sakshi_Assignment_78

src/denish/Assignment75.java
=> Denish_Assignment_75

src/sakshi/Assignment77.java
=> Sakshi_Assignment_77

src/denish/Assignment76.java
=> Denish_Assignment_76

src/onkar/Assignment78.java
=> Onkar_Assignment78

src/sakshi/Assignment76.java
=> Sakshi_Assignment_76

src/sakshi/Assignment75.java
=> Sakshi_Assignment_75

src/roshani/Ass77RemoveNameOccurance.java
=> Roshni_Assignment_77

src/onkar/Assignment77.java
=> Onkar_Assignment77

src/roshani/Ass76RemoveDuplicateArrayList.java
=> Roshni_Assignment_76

src/onkar/Assignment76.java
=> Onkar_Assignment76

src/aditya/Collection/Assignment73.java
=> Aditya_Assignment73

src/akshita/collection/Assignment71.java
Akshita_Assignment_71 return unique list of names from given ArrayList
=> Akshita_Assignment_71

src/sayali/Assignment78.java
=> Sayali_Assignment_78

src/denish/Assignment77.java
=> Denish_Assignment_77

src/denish/Assignment68SingletonDesignConnection.java
=> Denish_Assignment_68_modifyCode

src/aditya/Collection/Assignment72.java
=> Aditya_Assignment72

src/sayali/Assignment75.java
=> Sayali_Assignment_75

src/sayali/Assignment77.java
=> Sayali_Assignment_77

src/sayali/Assignment76.java
=> Sayali_Assignment_76

src/akshita/collection/Assignment70.java
Akshita_Assignment_70 print unique names from given ArrayList
=> Akshita_Assignment_70

src/pushpa/Assignment72.java
=> Pushpa Assignment72

src/pushpa/Assignment73.java
=> Pushpa Assignment73

src/pushpa/Assignment74.java
=> Pushpa Assignment74

src/pushpa/Assignment75.java
=> Pushpa Assignment75

src/pushpa/Assignment76.java
=> Pushpa Assignment76

src/pushpa/Assignment77.java
=> Pushpa Assignment77

src/pushpa/Assignment78.java
=> Pushpa Assignment78

src/roshani/Ass79FreqOfNoArrayList.java
=> Roshni_Assignment_79 : Print Freq of Num ArrayList

src/roshani/Ass80PrintFreqOfNameArrayList.java
=> Roshni_Assignment_80 : PrintFreqOfNames ArrayList

src/yogesh/Yogesh_Assigment79.java
=> Yogesh_Assignment79

src/yogesh/Yogesh_Assignment80.java
=> Yogesh_Assignment80

src/deepak/Assignment68_SingleTonDesignClient.java, src/deepak/Assignment68_SingleTonDesignConnection.java
=> Deepak_Assignment_68

src/deepak/Assignment69_SwitchCase.java
=> Deepak_Assignment_69

src/deepak/Assignment75_ReplaceObjectArrayList.java
=> Deepak_Assignment_75

src/deepak/Assignment76_RemoveDuplicate.java
=> Deepak_Assignment_76

src/deepak/Assignment77_RemoveFunction.java
=> Deepak_Assignment_77

src/deepak/Assignment78_ReplaceObject.java
=> Deepak_Assignment_78

src/deepak/Assignment79_PrintFrequencyNum.java
=> Deepak_Assignment_79

src/deepak/Assignment80_PrintFrequencyString.java
=> Deepak_Assignment_80

src/pushpa/Assignment79.java
=> Pushpa Assignment79

src/pushpa/Assignment80.java
=> Pushpa Assignment80

src/denish/Assignment78.java
=> Denish_Assignment_78

src/denish/Assignment79.java
=> Denish_Assignment_79

src/denish/Assignment80.java
=> Denish_Assignment_80

src/swati/Ass70UniqueNamesFromArrayList.java
=> Swati_Assignment_70

src/swati/Ass71ReturnUniqueListNames.java
=> Swati_Assignment_71

src/swati/Ass72RepetitiveName.java
=> Swati_Assignment_72

src/swati/Ass73InsertValueAtIndex.java
=> Swati_Assignment_73

src/swati/Ass74ArrayListPrimeNumber.java
=> Swati assignment 74

src/swati/Ass75ReplaceOccurance.java
=> Swati_Assignment_75

src/swati/Ass76RemoveDuplicates.java
=> Swati_Assignment_76

src/swati/Ass77RemoveAllOccurance.java
=> Swati_Assignment_77

src/swati/Ass78ReplaceOccurance.java
=> Swati_Assignment_78

src/swati/Ass79FreqOfEachNumber.java
=> Swati_Assignment_79

src/swati/Ass80FreqOfNameUsingArrayList.java
=> Swati_Assignment_80

src/swati/Ass81ReturnUniqueSetOfNumbers.java
=> Swati_assignment_81

src/hetal/Assignment70.java
=> Hetal_Assignment_70

src/hetal/Assignment71.java
=> Hetal_Assignment71

src/hetal/Assignment72.java
=> Hetal_Assignment72

src/subramanian/Assignment70.java
=> Subramanian_Assignment_70

src/sayali/Assignment79.java
=> Sayali_Assignment_79

src/sayali/Assignment80.java
=> Sayali_Assignment_80

src/subramanian/Assignment71.java
=> Subramanian_Assignment_71

src/gaurang/Assignment77.java
=> Assignment_77

src/denish/Assignment81.java
=> Denish_Assignment_81

src/denish/Assignment82.java
=> Denish_Assignment_82

src/gaurang/Assignment78.java
=> Assignment_78

src/sayali/Assignment81.java
=> Sayali_Assignment_81

src/hetal/Assignment73.java
=> Hetal_Assignment73

src/akshita/collection/Assignment73.java
Akshita_Assignment_73_    Insert number 100 at the index of first negative number
=> Akshita_Assignment_73_

src/sayali/Assignment82.java
=> Sayali_Assignment_82

src/hetal/Assignment74.java
=> Hetal_Assignment74

src/gaurang/Assignment79.java
=> Gaurang_Branch_80

src/gaurang/Assignment80.java
=> Assignment_80

src/gaurang/Assignment81.java
=> Assignment_81

src/gaurang/Assignment82.java
=> Assignment_82

src/akshita/collection/Assignment74.java
Akshita_Assignment_74 return the list of all the prime numbers in a give list
=> Akshita_Assignment_74

src/akshita/collection/Assignment75.java
Akshita_Assignment_75  given character having multiple occurrences then replace first occurr with character 'a' and last with 'b'
=> Akshita assignment 75

src/jaykumar/Assignment79.java
=> Jaykumar_Assignment79

src/jaykumar/Assignment80.java
=> Jaykumar_Assignment80

src/akshita/collection/Assignment76.java
Akshita_Assignment_76  Remove all the duplicate values from the list.
=> Akshita_Assignment_76

src/akshita/collection/Assignment77.java
Akshita_Assignment_77 Remove all occurrences of given name from Array List
=> Akshita_Assignment_77

src/akshita/collection/Assignment78.java
Akshita_Assignment_78 Remove all occurrences of given 'Gaurang' with 'Rahul' in a given ArrayList
=> Akshita_Assignment_78

src/jyoti_CollectionFrameWork/Assignment70.java
=> Jyoti_Assignment70

src/jaykumar/Assignment81.java
=> Jaykumar_Assignment81

src/jaykumar/Assignment82.java
=> Jaykumar_Assignment82

src/jyoti_CollectionFrameWork/Assignment71.java
=> Jyoti_Assignment71

src/jyoti_CollectionFrameWork/Assignment72.java
=> Jyoti_Assignment72

src/jyoti_CollectionFrameWork/Assignment73.java
=> Jyoti_Assignment73

src/jyoti_CollectionFrameWork/Assignment74.java
=> Jyoti_Assignment74

src/jyoti_CollectionFrameWork/Assignment75.java
=> Jyoti_Assignment75

src/jyoti_CollectionFrameWork/Assignment76.java
=> Jyoti_Assignment76

src/jyoti_CollectionFrameWork/Assignment77.java
=> Jyoti_Assignment77

src/jyoti_CollectionFrameWork/Assignment78.java
=> Jyoti_Assignment78

src/jyoti_CollectionFrameWork/Assignment79.java
=> Jyoti_Assignment79

src/jyoti_CollectionFrameWork/Assignment80.java
=> Jyoti_Assignment80

src/swati/Ass82ReturnDuplicateNum.java
=> Swati_Assignment_82

src/sakshi/Assignment79.java
=> Sakshi_Assignment_79

src/sakshi/Assignment80.java
=> Sakshi_Assignment_80

src/sakshi/Assignment81.java
=> Sakshi_Assignment_81

src/sakshi/Assignment82.java
=> Sakshi_Assignment_82

src/akshita/collection/Assignment79.java
Akshita_Assignment_79 print freq of each number using ArrayList
=> Akshita_Assignment_79

src/akshita/collection/Assignment80.java
Akshita_Assignment_80 Print freq of each name using ArrayList
=> Akshita_Assignment_80

src/akshita/collection/Assignment81.java
Akshita_Assignment_81 Return unique set of number from all given numbers
=> Akshita_Assignment_81

src/akshita/collection/Assignment82.java
Akshita_Assignment_82 Return all duplicate number
=> Akshita_Assignment_82

src/sakshi/Assignment83.java
=> Sakshi_Assignment83

src/sakshi/Assignment84.java
=> Sakshi_Assignment84

src/sakshi/Assignment85.java
=> Sakshi_Assignment85

src/sayali/Assignment83.java
=> Sayali_Assignment_83

src/sayali/Assignment84.java
=> Sayali_Assignment_84

src/sakshi/Assignment86.java
=> Sakshi_Assignment86

src/deepak/Assignment81_UniqueNumSet.java
=> Deepak_Assignment81

src/deepak/Assignment82_DuplicateNumSet.java
=> Deepak_Assignment82

src/deepak/Assignment83_CharacterFrequencyMap.java
=> Deepak_Assignment_83

src/deepak/Assignment84_WordFrequencyMap.java
=> Deepak_Assignment_84

src/deepak/Assignment85_NumberFrequencyMap.java
=> Deepak assignment 85

src/deepak/Assignment86_GetUniqueWords.java
=> Deepak_Assignment_86

src/deepak/Assignment87_GetWordWithMaxFrequency.java
=> Deepak_Assignment_87

src/deepak/Assignment88_GetWordWithMaxFrequency1.java
=> Deepak_Assignment_88

src/denish/Assignment85.java
=> Denish_assignment_85

src/denish/Assignment83.java
=> Denish_Assignment_83

src/denish/Assignment84.java
=> Denish_Assignment_new84

src/denish/Assignment86.java
=> Denish_Assignment_86

src/denish/Assignment87.java
=> Denish_Assignment_87

src/yogesh/Yogesh_Assignment81.java
=> Yogesh_Assignment81

src/yogesh/Yogesh_Assignment82.java
=> Yogesh_Assignment82

src/swati/Ass83FreqOfCharUsingMap.java
=> Swati_Assignment_83

src/swati/Ass84FreqOfEachWordUsingMap.java
=> Swati_Assignment_84

src/hetal/Assignment75.java
=> Hetal_Assignment75

src/hetal/Assignment76.java
=> Hetal_Assignment76

src/sayali/Assignment85.java
=> Sayali_Assignment_85

src/swati/Ass85FreqOFNumbUSingMap.java
=> Swati_Assignment_85

src/sayali/Assignment86.java
=> Sayali_Assignment86

src/sayali/Assignment87.java
=> Sayali_Assignment_87

src/shrutika/As73InsertValueAtIndex.java
=> Shrutika_Assignment_73

src/sayali/Assignment88.java
=> Sayali_Assignment_88

src/shrutika/As72RepetitiveName.java
=> Shrutika_Assignment_72

src/swati/Ass87WordWithMaxFreq.java
=> Swati_Assignment_87

src/shrutika/As71ReturnUniqueListName.java
=> Shrutika_Assignment_71

src/shrutika/As70UniqueNameFromArray.java
=> Shrutika_Assignment_70

src/shrutika/As69SwitchCase.java
=> Shrutika_Assignment_69

src/shrutika/As68Client.java, src/shrutika/As68SingleTonDesignPattern.java
=> Shrutika_Assignment_68

src/shrutika/As20CharFreq.java, src/shrutika/As21MaxFrequency.java, src/shrutika/As25CharFreqForLoop.java, src/shrutika/As66ReverseNumber.java
=> Shrutika_Assignment_66

src/hetal/Assignment77.java
=> Hetal_Assignment77

src/pushpa/Assignment88.java
=> Pushpa Assignment88

src/pushpa/Assignment87.java
=> Pushpa Assignment87

src/pushpa/Assignment83.java
=> Pushpa Assignment83

src/pushpa/Assignment84.java
=> Pushpa Assignment84

src/pushpa/Assignment85.java
=> Pushpa Assignment85

src/pushpa/Assignment86.java
=> Pushpa Assignment86

src/pushpa/Assignment82.java
=> Pushpa_Assignment82

src/pushpa/Assignment81.java
=> Pushpa Assignment81

src/swati/Ass88MaxFreqWordAndItsFreq.java
=> Swati_Assignment_88

src/swati/Ass86ListOfUniqueWords.java
=> Swati_Assignment_86

src/jaykumar/Assignment83.java
=> Jaykumar_Assignment83

src/shrutika/As74ArrayListPrimeNumb.java
=> Shrutika_Assignment_74

src/jaykumar/Assignment84.java
=> Jaykumar_Assignment84

src/shrutika/As75ReplaceOccurance.java
=> Shrutika_Assignment_75

src/shrutika/As76RemoveDuplicate.java
=> Shrutika_Assignment_76

src/shrutika/As77RemoveAllOccurance.java
=> Shrutika_Assignment_77

src/jaykumar/Assignment85.java
=> Jaykumar assignment85

src/jaykumar/Assignment86.java
=> Jaykumar_Assignment86

src/jaykumar/Assignment87.java
=> Jaykumar_Assignment87

src/jaykumar/Assignment88.java
=> Jaykumar_Assignment88

src/jyoti_CollectionFrameWork/Assignment81.java
=> Jyoti_Assignment81

src/jyoti_CollectionFrameWork/Assignment82.java
=> Jyoti_Assignment82

src/jyoti_CollectionFrameWork/Assignment83.java
=> Jyoti_Assignment83

src/shrutika/As78ReplaceOccurance.java
=> Shrutika assignment 78

src/shrutika/As79FreqOfEachNumb.java
=> Shrutika_Assignment_79

src/shrutika/As80FreqOfNameUsingArryList.java
=> Shrutika_Assignment_80

src/shrutika/As81ReturnUniqueSetOfNumb.java
=> Shrutika_Assignment_81

src/shrutika/As82ReturnDuplicateNumb.java
=> Shrutika_Assignment_82

src/aditya/Collection/Assignment75.java
=> Aditya_Assignment75

src/shrutika/As83FreqOfCharUsingMap.java
=> Shrutika_Assignment_83

src/shrutika/As84FreqOfEachWordUsingMap.java
=> Shrutika_Assignment_84

src/shrutika/As85FreqOfNumbUsingMap.java
=> Shrutika_Assignment_85

src/shrutika/As86ListOfUsingWords.java
=> Shrutika_Assignment_86

src/shrutika/As87WordWithMaxFreq.java
=> shrutika_Assignment_87

src/aditya/Collection/Assiggnment76.java
=> Aditya_Assignment76

src/shrutika/As88MaxFreqWordFreq.java
=> Shrutika_Assignment_88

src/aditya/Collection/Assignment77.java
=> Aditya_Assignment77

src/aditya/Collection/Assignment78.java
=> Aditya_Assignment78

src/jyoti_CollectionFrameWork/Assignment85.java
=> Jyoti_Assignment85

src/jyoti_CollectionFrameWork/Assignment86.java
=> Jyoti_Assignment86

src/jyoti_CollectionFrameWork/Assignment87.java
=> Jyoti_Assignment87

src/jyoti_CollectionFrameWork/Assignment88.java
=> Jyoti_Assignment88

src/jaykumar/Assignment89_Client.java, src/jaykumar/Assignment89_Employee.java
=> Jaykumar_Assignment89

src/jaykumar/Assignment90_Client.java, src/jaykumar/Assignment90_Student.java
=> Jaykumar_Assignment90

src/jaykumar/Assignment91_Client.java, src/jaykumar/Assignment91_Employee.java, src/jaykumar/Assignment91_ExpComparator.java, src/jaykumar/Assignment91_NameComparator.java, src/jaykumar/Assignment91_SalaryComparator.java
=> Jaykumar_Assignment91

src/denish/Assignment89_ClientEmployee.java, src/denish/Employee.java
=> Denish_Assignment_89

src/denish/Assignment90_Client.java, src/denish/Assignment90_Student.java
=> Denish_Assignment_90

src/denish/Ass91_Name_Comparator.java, src/denish/Ass91_Salary_Comparator.java, src/denish/Ass91_YearExp_Comparator.java, src/denish/Assignment91_Client.java, src/denish/Assignment91_Employee.java
=> Denish_Assignment_91

src/akshita/collection/Assignment83.java
Akshita_Assignment_83  Return freq of each character in a given String Return freq of each character in a given String
=> Akshita_Assignment_83

src/akshita/collection/Assignment84.java
Akshita_Assignment_84 Return freq of each word in a given String
=> Akshita_Assignment_84

src/akshita/collection/Assignment85.java
Akshita_Assignmet_85 Return freq of each number in a given array.
=> Akshita_Assignmet_85

src/akshita/collection/Assignment86.java
Akshita_Assignment_86 return list of all the unique (having freq =1) words  from given String
=> Akshita_Assignment_86

src/akshita/collection/Assignment87.java
Akshita_Assignment87 Return the word having Maximum frequency
=> Akshita_Assignment87

src/akshita/collection/Assignment88.java
Akshit_Assignment_88 Return the word having Maximum frequency and its frequency
=> Akshit_Assignment_88

src/aditya/Collection/Assignment79.java
=> Aditya_Assignment79

src/aditya/Collection/Assignment80.java
=> Aditya_Assignment80

src/nivedita/A69SwitchCase.java
=> Nivedita_Assignment_69

src/nivedita/A67TernaryOperator.java
=> Nivedita_Assignment_67

src/nivedita/A66ReturnNum.java
=> Nivedita_Assignment_66

src/nivedita/A65Palindrome.java
=> Nivedita_Assignment_65

src/nivedita/A64ArmstrongNum.java
=> Nivedita_Assignment_64

src/onkar/Assignment80.java
=> Onkar_Assignment80

src/aditya/Collection/Assignment81.java
=> Aditya_Assignment81

src/swati_Collections/Ass89Employee.java, src/swati_Collections/Ass89Employee_Client.java
=> Swati_Assignment_89

src/swati_Collections/Ass90Student.java, src/swati_Collections/Ass90Student_Client.java
=> Swati_Assignment_90

src/shrutika/As89Client.java, src/shrutika/As89SetOfEmp.java
=> Shrutika_Assignment_89

src/onkar/Assignment83.java
=> Onkar_Assignment83

src/onkar/Assignment84.java
=> Onkar_Assignment84

src/onkar/Assignment85.java
=> Onkar_Assignment85

src/sayali/Assignment89_Client.java, src/sayali/Assignment89_Employee.java
=> Sayali_Assignment_89

src/aditya/Collection/Assignment82.java
=> Aditya_Assignment82

src/sayali/Assignment90_Client.java, src/sayali/Assignment90_Student.java
=> Sayali_Assignment_90

src/sayali/Assignment91_Client.java, src/sayali/Assignment91_Employee.java, src/sayali/Assignment91_ExperienceComparator.java, src/sayali/Assignment91_NameComparator.java, src/sayali/Assignment91_SalaryComparator.java
=> Sayali_Assignment_91

src/onkar/Assignment86.java
=> Onkar_Assignment86

src/onkar/Assignment87.java
=> Onkar_Assignment87

src/onkar/Assignment88.java
=> Onkar_Assignment88

src/hetal/Assignment78.java
=> Hetal_Assignment78

src/nivedita/A70PrintNames.java
=> Nivedita_Assignment_70

src/nivedita/A75ReplaceChar.java
=> Nivedita_Assignment_75

src/nivedita/A74ReturnPrimeNum.java
=> Nivedita_Assignment_74

src/nivedita/A73InsertNum.java
=> Nivedita_Assignment_73

src/nivedita/A72ReturnNames.java
=> Nivedita_Assignment_72

src/nivedita/A71ReturnList.java
=> Nivedita_Assignment_71

src/nivedita/A79FreqOfEachNumber.java
=> Nivedita_Assignment_79

src/nivedita/A78RemoveSTring.java
=> Nivedita_Assignment_78

src/nivedita/A77RemoveString.java
=> Nivedita_Assignment_77

src/nivedita/A80FreqOfNameUsingArrayList.java
=> Nivedita_Assignment_80

src/nivedita/A81ReturnUniqueSetNum.java
=> Nivedita_Assignment_81

src/shrutika/As90Client.java, src/shrutika/As90Student.java
=> Shrutika_Assignment_90

src/shrutika/As91Client.java, src/shrutika/As91Employee.java, src/shrutika/As91ExpComparator.java, src/shrutika/As91NameComparator.java, src/shrutika/As91SalaryComparator.java
=> Shrutika_Assignment_91

src/pushpa/Assignment89_Employee.java, src/pushpa/Assignment89_Main.java
=> Pushpa Assignment89

src/pushpa/Assignment90_Main.java, src/pushpa/Assignment90_Student.java
=> Pushpa Assignment90

src/swati/Ass95PrintLineWithMaxWord.java, src/swati/readmepractice3.txt
=> Swati_Assignment_95

src/denish/Assignment94_Duplicate_Word.java, src/denish/practis.txt
=> Denish_Assignment_94

src/denish/Assignment93_Test_File.java, src/denish/reamData.txt
=> Denish_Assignment_93

src/denish/Assignment92_Data_Operation.java, src/denish/config.properties
=> Denish_Assignment_92

src/rahul/AllFiles/propertyFile1, src/rahul/AllFiles/propertyFile2, src/rahul/AllFiles/textFile1, src/rahul/Assignment92_1.java, src/rahul/Assignment92_2.java, src/rahul/Assignment92_3.java
=> Rahul_Assignment-92

src/shrutika/As92DataOperation.java, src/shrutika/As92TestData.Properties
=> Shrutika assignment 92

src/swati/Ass94DuplicateWordTextFileRead.java, src/swati/readmepractice2.txt
=> Swati_Assignment_94

src/swati/Ass93LoadTestFile.java, src/swati/readmepractice1.txt
=> Swati_Assignment_93

src/swati/Ass92LoadPropertiesFile.java, src/swati/configFile1.properties, src/swati/configFile2.properties
=> Swati_Assignment_92

src/shrutika/As93ReadingTheFile.java, src/shrutika/As93UserFile.txt
=> Shrutika_Assignment_93

src/shrutika/As94FrequencyOfWord.java, src/shrutika/As94UserFile2.txt
=> Shrutika_Assignment_94

src/shrutika/As95MaxWordInFile.java, src/shrutika/As95UserFile3.txt
=> Shrutika assignment 95

src/sayali/Ass92PropertiesFile.java, src/sayali/configFile1.properties, src/sayali/configFile2.properties
=> Sayali_Assignment_92

src/sayali/Ass93LoadTextFile.java, src/sayali/Ass93PracticeTextFile.txt
=> Sayali_Assignment_93

src/sayali/Ass94ReadDuplicateWordInFile.java, src/sayali/Ass94SampleTextFile1.txt
=> Sayali_Assignment_94

src/sayali/Ass95PrintLineHavingMaxWords.java, src/sayali/Ass95SampleTextFile2.txt
=> Sayali_Assignment_95

src/onkar/Assignment89.java, src/onkar/Assignment89_Client.java
=> Onkar_Assignment89

src/swati_Collections/Ass91Client.java, src/swati_Collections/Ass91Employee.java, src/swati_Collections/Ass91NameComp.java, src/swati_Collections/Ass91SalaryComp.java, src/swati_Collections/Ass91yearsOfExpComp.java
=> Swati_Assignment_91
